var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/reminders/route.js")
R.c("server/chunks/[root-of-the-server]__ad584214._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_7f1565d1._.js")
R.c("server/chunks/_2b2fdc7d._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__42a428ae._.js")
R.c("server/chunks/_next-internal_server_app_api_cron_reminders_route_actions_10b682dc.js")
R.m(51646)
module.exports=R.m(51646).exports
