var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/checkout/route.js")
R.c("server/chunks/[root-of-the-server]__34658a4c._.js")
R.c("server/chunks/[root-of-the-server]__c7379e06._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_2b2fdc7d._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__42a428ae._.js")
R.c("server/chunks/_next-internal_server_app_api_checkout_route_actions_414bfd84.js")
R.m(63437)
module.exports=R.m(63437).exports
