const getDbPool = require('./app/lib/db.ts').default;
import { Pool } from 'pg';

async function runSql(pool: Pool, sqlQuery: string) {
    let client;
    try {
        client = await pool.connect();
        await client.query(sqlQuery);
        console.log(`\n✅ SQL executed successfully: ${sqlQuery.substring(0, 50)}...`);
    } catch (error) {
        console.error(`\n❌ SQL execution failed: ${sqlQuery.substring(0, 50)}...`, error);
        throw error;
    } finally {
        if (client) client.release();
    }
}

const schemaCommands = [
    "CREATE TABLE IF NOT EXISTS sessions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, category TEXT, instructor TEXT, start_time TIMESTAMP WITH TIME ZONE NOT NULL, end_time TIMESTAMP WITH TIME ZONE NOT NULL, image_url TEXT, description TEXT);",
    "CREATE TABLE IF NOT EXISTS profiles (id UUID REFERENCES auth.users(id) PRIMARY KEY, username TEXT UNIQUE NOT NULL, avatar_url TEXT);",
    "CREATE TABLE IF NOT EXISTS posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES profiles(id), image_url TEXT, caption TEXT, created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()), shared_post_id BIGINT REFERENCES posts(id));",
    "CREATE TABLE IF NOT EXISTS likes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES profiles(id), post_id BIGINT REFERENCES posts(id), created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()), UNIQUE(user_id, post_id));",
    "CREATE TABLE IF NOT EXISTS messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender_id TEXT, receiver_id TEXT, content TEXT, image_url TEXT, created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()));",
    "CREATE TABLE IF NOT EXISTS registrations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL, session_id BIGINT REFERENCES sessions(id) ON DELETE CASCADE NOT NULL, registered_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()), UNIQUE(user_id, session_id));",
    "INSERT INTO profiles (id, username, avatar_url) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Lee Wong', 'https://placehold.co/100');",
    "INSERT INTO sessions (id, title, category, instructor, start_time, end_time, image_url, description) VALUES (1, 'Pro Hockey Drills', 'ADULT', 'Coach Alex', '2025-12-10T18:00:00Z', '2025-12-10T19:00:00Z', 'https://placehold.co/400x200/28D160/white?text=ADULT+DRILL', 'High-intensity skill work.'), (2, 'Youth Fundamentals', 'YOUTH', 'Coach Ben', '2025-12-11T16:00:00Z', '2025-12-11T17:00:00Z', 'https://placehold.co/400x200/146B31/white?text=YOUTH+CLASS', 'Focus on skating and puck control.');"
];

(async () => {
    const pool = getDbPool();
    try {
        console.log("--- Starting Database Schema Initialization ---");
        for (const cmd of schemaCommands) {
            await runSql(pool, cmd);
        }
        console.log("--- Schema Initialization Complete! ---");
    } catch (e) {
        console.error("\n*** FATAL ERROR DURING SCHEMA BUILD ***\n", e);
    } finally {
        await pool.end();
    }
})();