const getDbPool = require('./app/lib/db.ts').default;
import { Pool } from 'pg';

// --- CONFIGURATION: FIXED USER IDs ---
// These match the UUIDs used in your seed data so relationships stay intact.
const TEST_USER_ID = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'; 
const TEST_USER_ID_2 = 'a1b2c3d4-e5f6-7890-1234-567890abcdef'; 

// --- TRIGGER LOGIC (Auto-create profile on signup) ---
const TRIGGER_SQL = [
    `
    CREATE OR REPLACE FUNCTION public.handle_new_user() 
    RETURNS trigger AS $$
    BEGIN
      INSERT INTO public.profiles (id, contact_email, first_name, last_name, username, avatar_url)
      VALUES (
        NEW.id, 
        NEW.email,
        split_part(NEW.email, '@', 1),
        '',
        split_part(NEW.email, '@', 1),
        'https://placehold.co/100'
      )
      ON CONFLICT (id) DO NOTHING;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
    `,
    `DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;`,
    `
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW
      EXECUTE PROCEDURE public.handle_new_user();
    `
];

const schemaCommands = [
    // 0. CRITICAL: Enable Encryption for Passwords
    `CREATE EXTENSION IF NOT EXISTS "pgcrypto";`,

    // 1. Reset Tables (Clean Slate)
    "DROP TABLE IF EXISTS registrations CASCADE;",
    "DROP TABLE IF EXISTS players_stats CASCADE;",
    "DROP TABLE IF EXISTS sessions CASCADE;",
    "DROP TABLE IF EXISTS profiles CASCADE;",
    "DROP TABLE IF EXISTS posts CASCADE;",
    "DROP TABLE IF EXISTS likes CASCADE;",
    "DROP TABLE IF EXISTS messages CASCADE;",

    // 2. Create Tables (UPDATED WITH STRIPE COLUMNS)
    `CREATE TABLE profiles (
        id UUID REFERENCES auth.users(id) PRIMARY KEY,
        username TEXT, first_name TEXT, last_name TEXT, 
        mobile TEXT, contact_email TEXT, avatar_url TEXT, bio TEXT,
        tier TEXT DEFAULT 'free',
        stripe_customer_id TEXT,
        subscription_status TEXT DEFAULT 'inactive',
        credits INTEGER DEFAULT 0
    );`,
    
    `CREATE TABLE sessions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
        title TEXT NOT NULL, 
        category TEXT, 
        instructor TEXT, 
        start_time TIMESTAMP WITH TIME ZONE NOT NULL, 
        end_time TIMESTAMP WITH TIME ZONE NOT NULL, 
        image_url TEXT, 
        description TEXT
    );`,

    `CREATE TABLE registrations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
        user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL, 
        session_id BIGINT REFERENCES sessions(id) ON DELETE CASCADE NOT NULL, 
        registered_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()), 
        UNIQUE(user_id, session_id)
    );`,

    `CREATE TABLE players_stats (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        player_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, 
        age INTEGER, season INTEGER, team TEXT,
        games_played_season INTEGER, games_played_total INTEGER,
        games_missed_healthy INTEGER, games_missed_injured INTEGER,
        goals_season INTEGER, goals_total INTEGER,
        assists_season INTEGER, assists_total INTEGER,
        gp INTEGER, points INTEGER, gwg INTEGER, ppg INTEGER, shg INTEGER, pim INTEGER,
        top_scorer_team BOOLEAN, top_scorer_league BOOLEAN, least_pim_team BOOLEAN, most_shots_team BOOLEAN,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );`,

    `CREATE TABLE posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES profiles(id), image_url TEXT, caption TEXT, created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()), shared_post_id BIGINT REFERENCES posts(id));`,
    `CREATE TABLE likes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES profiles(id), post_id BIGINT REFERENCES posts(id), UNIQUE(user_id, post_id));`,
    `CREATE TABLE messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender_id UUID, receiver_id UUID, content TEXT, image_url TEXT, created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()), shared_event_id BIGINT);`,

    // 3. Disable RLS (For easier local dev)
    `ALTER TABLE registrations DISABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE posts DISABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE players_stats DISABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE messages DISABLE ROW LEVEL SECURITY;`,

    // 4. Storage Bucket Setup
    `INSERT INTO storage.buckets (id, name, public) VALUES ('uploads', 'uploads', true) ON CONFLICT (id) DO NOTHING;`,
    `DROP POLICY IF EXISTS "Public Access" ON storage.objects;`,
    `CREATE POLICY "Public Access" ON storage.objects FOR ALL USING ( bucket_id = 'uploads' ) WITH CHECK ( bucket_id = 'uploads' );`,
    
    // --- INSERT DATABASE TRIGGER LOGIC ---
    ...TRIGGER_SQL,

    // 5. AUTH MAGIC: Create Users (This restores logins if DB is wiped)
    // User 1: Lee
    `INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
     VALUES ('00000000-0000-0000-0000-000000000000', '${TEST_USER_ID}', 'authenticated', 'authenticated', 'lee@east.com', crypt('password123', gen_salt('bf')), current_timestamp, current_timestamp, current_timestamp, '{"provider":"email","providers":["email"]}', '{}', current_timestamp, current_timestamp, '', '', '', '')
     ON CONFLICT (id) DO NOTHING;`,

    `INSERT INTO auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
     VALUES ('d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4', '${TEST_USER_ID}', format('{"sub":"%s","email":"%s"}', '${TEST_USER_ID}', 'lee@east.com')::jsonb, 'email', 'lee@east.com', current_timestamp, current_timestamp, current_timestamp)
     ON CONFLICT (id) DO NOTHING;`,

    // User 2: Coach
    `INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
     VALUES ('00000000-0000-0000-0000-000000000000', '${TEST_USER_ID_2}', 'authenticated', 'authenticated', 'coach@test.com', crypt('password123', gen_salt('bf')), current_timestamp, current_timestamp, current_timestamp, '{"provider":"email","providers":["email"]}', '{}', current_timestamp, current_timestamp, '', '', '', '')
     ON CONFLICT (id) DO NOTHING;`,

    `INSERT INTO auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
     VALUES ('e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5', '${TEST_USER_ID_2}', format('{"sub":"%s","email":"%s"}', '${TEST_USER_ID_2}', 'coach@test.com')::jsonb, 'email', 'coach@test.com', current_timestamp, current_timestamp, current_timestamp)
     ON CONFLICT (id) DO NOTHING;`,

    // 6. SEED DATA: Profiles & Stats
    // Note: We use UPDATE SET to ensure Stripe columns are initialized correctly
    `INSERT INTO profiles (id, username, first_name, last_name, mobile, contact_email, bio, avatar_url) 
     VALUES ('${TEST_USER_ID}', 'lee.wong12', 'Lee', 'Wong', '+1 234 567 8900', 'lee@east.com', 'Defenseman for the Rhinos.', 'https://placehold.co/100') 
     ON CONFLICT (id) DO UPDATE SET 
     username = EXCLUDED.username, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, mobile = EXCLUDED.mobile, bio = EXCLUDED.bio, avatar_url = EXCLUDED.avatar_url;`,
    
    `INSERT INTO players_stats (player_id, age, season, team, games_played_season, goals_season, points)
     VALUES ('${TEST_USER_ID}', 31, 3, 'RHINOS', 48, 110, 6)
     ON CONFLICT (id) DO NOTHING;`,
     
    `INSERT INTO profiles (id, username, first_name, last_name, mobile, contact_email, bio, avatar_url) 
     VALUES ('${TEST_USER_ID_2}', 'coach.test', 'Coach', 'Test', '+1 987 654 3210', 'coach@test.com', 'Head Coach', 'https://images.unsplash.com/photo-1595856552273-97b77df797b5?w=400&q=80') 
     ON CONFLICT (id) DO UPDATE SET 
     username = EXCLUDED.username, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, mobile = EXCLUDED.mobile, bio = EXCLUDED.bio, avatar_url = EXCLUDED.avatar_url;`,
    
    `INSERT INTO players_stats (player_id, age, season, team, games_played_season, goals_season, points)
     VALUES ('${TEST_USER_ID_2}', 45, 10, 'SHARKS', 90, 10, 50)
     ON CONFLICT (id) DO NOTHING;`,

    // 7. SEED DATA: Sessions (News, Events, Classes)
    // --- NEWS ---
    `INSERT INTO sessions (title, category, instructor, start_time, end_time, image_url, description) VALUES 
     ('Championship Win', 'NEWS', 'League', NOW(), NOW() + interval '14 days', 'https://images.unsplash.com/photo-1515523110800-9415d13b84a8?w=800&q=80', 'The Rhinos take home the trophy in a stunning overtime victory against the Wolves. It was a hard-fought battle that came down to the final seconds, securing their place in league history as the 2025 champions.'),
     ('New Rink Opening', 'NEWS', 'Management', NOW(), NOW() + interval '14 days', 'https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?w=800&q=80', 'East Sports expands with a brand new Olympic-sized ice surface opening this Friday. Features include upgraded locker rooms, a new pro shop, and state-of-the-art glass boards for better spectator viewing.');`,

    // --- EVENTS ---
    `INSERT INTO sessions (title, category, instructor, start_time, end_time, image_url, description) VALUES 
     ('Dragons Den', 'EVENT', 'Bolt Sports', NOW() + interval '5 days 18:00:00', NOW() + interval '5 days 21:00:00', 'https://images.unsplash.com/photo-1542557685-d72b22529949?w=800&q=80', 'Bolt Sports Leaderboard competition.'),
     ('East Golf League', 'EVENT', 'East Sports', NOW() + interval '7 days 09:00:00', NOW() + interval '7 days 14:00:00', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=80', 'Annual East Classic 2025.'),
     ('OPS Charts', 'EVENT', 'Tech Team', NOW() + interval '12 days 10:00:00', NOW() + interval '12 days 12:00:00', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', 'Performance analysis workshop.'),
     ('Ryder Cup Watch', 'EVENT', 'Social Comm', NOW() + interval '15 days 20:00:00', NOW() + interval '15 days 23:00:00', 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80', 'Ryder Cup Watch Party on the big screen.');`,

    // --- FACILITIES ---
    `INSERT INTO sessions (title, category, instructor, start_time, end_time, image_url, description) VALUES 
     ('Shooting Pad', 'FACILITY', 'Staff', NOW() + interval '1 day 10:00:00', NOW() + interval '1 day 11:00:00', 'https://images.unsplash.com/photo-1547941126-be8c96fd69ac?w=600&q=80', 'Book a lane for stick handling.'),
     ('Shooting Pad', 'FACILITY', 'Staff', NOW() + interval '1 day 11:00:00', NOW() + interval '1 day 12:00:00', 'https://images.unsplash.com/photo-1547941126-be8c96fd69ac?w=600&q=80', 'Book a lane for stick handling.'),
     ('Shooting Pad', 'FACILITY', 'Staff', NOW() + interval '1 day 14:00:00', NOW() + interval '1 day 15:00:00', 'https://images.unsplash.com/photo-1547941126-be8c96fd69ac?w=600&q=80', 'Book a lane for stick handling.'),
     ('Golf Simulator', 'FACILITY', 'Staff', NOW() + interval '1 day 12:00:00', NOW() + interval '1 day 13:00:00', 'https://images.unsplash.com/photo-1593111774240-d529f12db4bb?w=600&q=80', 'Trackman simulator rental.'),
     ('Golf Simulator', 'FACILITY', 'Staff', NOW() + interval '1 day 13:00:00', NOW() + interval '1 day 14:00:00', 'https://images.unsplash.com/photo-1593111774240-d529f12db4bb?w=600&q=80', 'Trackman simulator rental.'),
     ('Locker Rental', 'FACILITY', 'Staff', NOW() + interval '1 day 08:00:00', NOW() + interval '1 day 22:00:00', 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=600&q=80', 'Day use locker.');`,

    // --- ADULT CLASSES ---
    `INSERT INTO sessions (title, category, instructor, start_time, end_time, image_url, description) VALUES 
     ('HYROX', 'ADULT', 'Coach Ben', NOW() + interval '2 days 18:00:00', NOW() + interval '2 days 19:00:00', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80', 'High intensity functional fitness.'),
     ('HYROX', 'ADULT', 'Coach Ben', NOW() + interval '3 days 18:00:00', NOW() + interval '3 days 19:00:00', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80', 'High intensity functional fitness.'),
     ('Strength', 'ADULT', 'Coach Rhett', NOW() + interval '2 days 19:00:00', NOW() + interval '2 days 20:00:00', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80', 'Heavy lifting focus.'),
     ('Speed', 'ADULT', 'Coach Whitney', NOW() + interval '4 days 07:00:00', NOW() + interval '4 days 08:00:00', 'https://images.unsplash.com/photo-1552674605-4696063e6719?w=600&q=80', 'Agility and sprint work.'),
     ('Stamina', 'ADULT', 'Coach Jeff', NOW() + interval '2 days 20:00:00', NOW() + interval '2 days 21:00:00', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80', 'Endurance training.'),
     ('Core', 'ADULT', 'Coach Fiona', NOW() + interval '3 days 08:00:00', NOW() + interval '3 days 09:00:00', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80', 'Abdominal focus.'),
     ('Upper Body', 'ADULT', 'Coach Jen', NOW() + interval '5 days 17:00:00', NOW() + interval '5 days 18:00:00', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80', 'Arms, chest and back.'),
     ('Legs', 'ADULT', 'Coach Brendon', NOW() + interval '5 days 18:00:00', NOW() + interval '5 days 19:00:00', 'https://images.unsplash.com/photo-1434608519344-49d77a699ded?w=600&q=80', 'Squats and lunges.'),
     ('FITIN6', 'ADULT', 'Coach Ryan', NOW() + interval '6 days 12:00:00', NOW() + interval '6 days 12:45:00', 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?w=600&q=80', '6 week transformation class.');`,

    // --- YOUTH CLASSES ---
    `INSERT INTO sessions (title, category, instructor, start_time, end_time, image_url, description) VALUES 
     ('Youth HYROX', 'YOUTH', 'Coach Jesse', NOW() + interval '2 days 16:00:00', NOW() + interval '2 days 17:00:00', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80', 'Intro to functional fitness.'),
     ('Youth Strength', 'YOUTH', 'Coach Lucas', NOW() + interval '3 days 16:00:00', NOW() + interval '3 days 17:00:00', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80', 'Safe lifting techniques.'),
     ('Youth Speed', 'YOUTH', 'Coach Whitney', NOW() + interval '4 days 16:00:00', NOW() + interval '4 days 17:00:00', 'https://images.unsplash.com/photo-1552674605-4696063e6719?w=600&q=80', 'Running mechanics.'),
     ('Youth Upper', 'YOUTH', 'Coach Jen', NOW() + interval '5 days 16:00:00', NOW() + interval '5 days 17:00:00', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80', 'Pushups and pullups.'),
     ('Youth Legs', 'YOUTH', 'Coach Brendon', NOW() + interval '6 days 10:00:00', NOW() + interval '6 days 11:00:00', 'https://images.unsplash.com/photo-1434608519344-49d77a699ded?w=600&q=80', 'Plyometrics and jumping.'),
     ('Youth FITIN6', 'YOUTH', 'Coach Ryan', NOW() + interval '6 days 11:00:00', NOW() + interval '6 days 11:45:00', 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?w=600&q=80', 'Circuit training.');`,

    // --- PRIVATE COACHES ---
    `INSERT INTO sessions (title, category, instructor, start_time, end_time, image_url, description) VALUES 
     ('Private Session', 'COACH', 'Ben', NOW() + interval '1 day 09:00:00', NOW() + interval '1 day 10:00:00', 'https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=400&q=80', '1-on-1 Coaching.'),
     ('Private Session', 'COACH', 'Ben', NOW() + interval '1 day 14:00:00', NOW() + interval '1 day 15:00:00', 'https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=400&q=80', '1-on-1 Coaching.'),
     ('Private Session', 'COACH', 'Rhett', NOW() + interval '2 days 10:00:00', NOW() + interval '2 days 11:00:00', 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400&q=80', 'Hockey skills.'),
     ('Private Session', 'COACH', 'Rhett', NOW() + interval '2 days 13:00:00', NOW() + interval '2 days 14:00:00', 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400&q=80', 'Hockey skills.'),
     ('Private Session', 'COACH', 'Whitney', NOW() + interval '3 days 11:00:00', NOW() + interval '3 days 12:00:00', 'https://images.unsplash.com/photo-1595856552273-97b77df797b5?w=400&q=80', 'Power skating.'),
     ('Private Session', 'COACH', 'Jeff', NOW() + interval '3 days 15:00:00', NOW() + interval '3 days 16:00:00', 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400&q=80', 'Defensive tactics.'),
     ('Private Session', 'COACH', 'Fiona', NOW() + interval '4 days 09:00:00', NOW() + interval '4 days 10:00:00', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80', 'Figure skating elements.'),
     ('Private Session', 'COACH', 'Jen', NOW() + interval '4 days 14:00:00', NOW() + interval '4 days 15:00:00', 'https://images.unsplash.com/photo-1594824476961-b7b8a537ccb9?w=400&q=80', 'Strength conditioning.'),
     ('Private Session', 'COACH', 'Brendon', NOW() + interval '5 days 11:00:00', NOW() + interval '5 days 12:00:00', 'https://images.unsplash.com/photo-1566938064504-a38b52123537?w=400&q=80', 'Off-ice training.'),
     ('Private Session', 'COACH', 'Ryan Wong', NOW() + interval '5 days 13:00:00', NOW() + interval '5 days 14:00:00', 'https://images.unsplash.com/photo-1600965962102-9d260a71890d?w=400&q=80', 'Performance analysis.'),
     ('Private Session', 'COACH', 'Jesse', NOW() + interval '6 days 10:00:00', NOW() + interval '6 days 11:00:00', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80', 'Youth development.'),
     ('Private Session', 'COACH', 'Lucas', NOW() + interval '6 days 15:00:00', NOW() + interval '6 days 16:00:00', 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&q=80', 'Goalie coaching.');`,

    // Refresh Schema (Final Step)
    `NOTIFY pgrst, 'reload schema';`
];

async function runSql(pool: Pool, sqlQuery: string) {
    const client = await pool.connect();
    try { await client.query(sqlQuery); console.log(`✅ Executed: ${sqlQuery.substring(0, 50)}...`); } 
    catch (e) { console.error(`❌ Failed: ${sqlQuery.substring(0, 50)}...`, e); } 
    finally { client.release(); }
}

(async () => {
    const pool = getDbPool();
    // Execute all schema commands and the new trigger commands
    const allCommands = [...schemaCommands, ...TRIGGER_SQL];
    for (const cmd of allCommands) await runSql(pool, cmd);
    await pool.end();
})();