var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/metrics/route.js")
R.c("server/chunks/[root-of-the-server]__f0a384c4._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_747dfdbc.js")
R.c("server/chunks/[root-of-the-server]__42a428ae._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_metrics_route_actions_e6fed316.js")
R.m(10386)
module.exports=R.m(10386).exports
