// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin-debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-debug">> = Specific
  const handler = {} as typeof import("../../../app/admin-debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-login">> = Specific
  const handler = {} as typeof import("../../../app/admin-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin-ops/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-ops/bookings">> = Specific
  const handler = {} as typeof import("../../../app/admin-ops/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin-ops/coaches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-ops/coaches">> = Specific
  const handler = {} as typeof import("../../../app/admin-ops/coaches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin-ops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-ops">> = Specific
  const handler = {} as typeof import("../../../app/admin-ops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin-ops/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-ops/schedule">> = Specific
  const handler = {} as typeof import("../../../app/admin-ops/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin-ops/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-ops/services">> = Specific
  const handler = {} as typeof import("../../../app/admin-ops/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/update-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/update-password">> = Specific
  const handler = {} as typeof import("../../../app/auth/update-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../../app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/check-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/check-in">> = Specific
  const handler = {} as typeof import("../../../app/check-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../../app/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/membership/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/membership">> = Specific
  const handler = {} as typeof import("../../../app/membership/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/membership/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/membership/success">> = Specific
  const handler = {} as typeof import("../../../app/membership/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/profile/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/[id]">> = Specific
  const handler = {} as typeof import("../../../app/profile/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/public/coach/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/coach/[id]">> = Specific
  const handler = {} as typeof import("../../../app/public/coach/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/public/player/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/player/[id]">> = Specific
  const handler = {} as typeof import("../../../app/public/player/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/statistics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/statistics">> = Specific
  const handler = {} as typeof import("../../../app/statistics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../../app/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/audit">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/bookings">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/coaches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/coaches">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/coaches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/directory">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/events">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/leaderboard">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/metrics">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/news">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/player-stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/player-stats">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/player-stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/players/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/players">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/players/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/qr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/qr">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/qr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/schedule">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/services">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/stats">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sys-admin/transactions">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/system-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system-check">> = Specific
  const handler = {} as typeof import("../../../app/system-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-auth">> = Specific
  const handler = {} as typeof import("../../../app/test-auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-direct/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-direct">> = Specific
  const handler = {} as typeof import("../../../app/test-direct/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/top-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/top-up">> = Specific
  const handler = {} as typeof import("../../../app/top-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin-ops/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin-ops/bookings">> = Specific
  const handler = {} as typeof import("../../../app/api/admin-ops/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/adjust-credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/adjust-credits">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/adjust-credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bookings">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/coach-availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/coach-availability">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/coach-availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/create-coach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-coach">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/create-coach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/create-player/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-player">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/create-player/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/delete-coach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/delete-coach">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/delete-coach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/delete-player/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/delete-player">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/delete-player/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/generate-schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/generate-schedule">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/generate-schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/leaderboard">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/ocr-stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ocr-stats">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/ocr-stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/player-stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/player-stats">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/player-stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/portal">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/schedule">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/send-reset-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/send-reset-email">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/send-reset-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sessions">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/transactions">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/update-coach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/update-coach">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/update-coach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/update-player/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/update-player">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/update-player/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements">> = Specific
  const handler = {} as typeof import("../../../app/api/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/request-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/request-reset">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/request-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/send-welcome-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-welcome-email">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/send-welcome-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/check-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/check-in">> = Specific
  const handler = {} as typeof import("../../../app/api/check-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/coach/master-schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coach/master-schedule">> = Specific
  const handler = {} as typeof import("../../../app/api/coach/master-schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/coach/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coach/notes">> = Specific
  const handler = {} as typeof import("../../../app/api/coach/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/coaches/available/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coaches/available">> = Specific
  const handler = {} as typeof import("../../../app/api/coaches/available/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/reminders">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-email">> = Specific
  const handler = {} as typeof import("../../../app/api/debug-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug-env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-env">> = Specific
  const handler = {} as typeof import("../../../app/api/debug-env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug">> = Specific
  const handler = {} as typeof import("../../../app/api/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/family/add-child/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/add-child">> = Specific
  const handler = {} as typeof import("../../../app/api/family/add-child/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/family/provision-player/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/provision-player">> = Specific
  const handler = {} as typeof import("../../../app/api/family/provision-player/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/family/transfer-credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/transfer-credits">> = Specific
  const handler = {} as typeof import("../../../app/api/family/transfer-credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/my-schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/my-schedule">> = Specific
  const handler = {} as typeof import("../../../app/api/my-schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/player-stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/player-stats">> = Specific
  const handler = {} as typeof import("../../../app/api/player-stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/register">> = Specific
  const handler = {} as typeof import("../../../app/api/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sessions/book/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/book">> = Specific
  const handler = {} as typeof import("../../../app/api/sessions/book/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sessions/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/sessions/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sessions/pay-via-qr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/pay-via-qr">> = Specific
  const handler = {} as typeof import("../../../app/api/sessions/pay-via-qr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions">> = Specific
  const handler = {} as typeof import("../../../app/api/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stripe/test-confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/test-confirm">> = Specific
  const handler = {} as typeof import("../../../app/api/stripe/test-confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/repair-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/repair-profile">> = Specific
  const handler = {} as typeof import("../../../app/api/user/repair-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/transactions">> = Specific
  const handler = {} as typeof import("../../../app/api/user/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/transfer-credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/transfer-credits">> = Specific
  const handler = {} as typeof import("../../../app/api/user/transfer-credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/inngest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/inngest">> = Specific
  const handler = {} as typeof import("../../../app/inngest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin-ops/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin-ops">> = Specific
  const handler = {} as typeof import("../../../app/admin-ops/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/check-in/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/check-in">> = Specific
  const handler = {} as typeof import("../../../app/check-in/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sys-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sys-admin">> = Specific
  const handler = {} as typeof import("../../../app/sys-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
