var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/sessions/route.js")
R.c("server/chunks/[root-of-the-server]__99b4b3f3._.js")
R.c("server/chunks/_7f1565d1._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__42a428ae._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_sessions_route_actions_e9d8295c.js")
R.m(7176)
module.exports=R.m(7176).exports
