-- ==============================================================================
-- EAST APP HONG KONG - CURRENT DATABASE SCHEMA (Source of Truth)
-- Generated: Jan 7, 2026
-- ==============================================================================
-- INSTRUCTIONS:
-- 1. Run this entire file in the Supabase SQL Editor.
-- 2. It is safe to run on an existing database (idempotent).
-- 3. It explicitly handles function signature updates (DROP then CREATE).
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES (Safe Schema Patching)
-- We use CREATE TABLE IF NOT EXISTS for new tables
-- And DO blocks for adding columns to existing tables safely.

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name text,
    last_name text,
    role text CHECK (role IN ('player', 'coach', 'parent', 'sys-admin')) DEFAULT 'player',
    credits integer DEFAULT 0,
    team text,
    position text,
    avatar_url text,
    created_at timestamp with time zone DEFAULT now(),
    parent_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    contact_email text,
    phone text,
    emergency_contact text,
    schedule_photo_url text,
    membership_tier text CHECK (membership_tier IN ('individual', 'family_2', 'family_3plus')) DEFAULT 'individual'
);

CREATE TABLE IF NOT EXISTS public.sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    description text,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    max_capacity integer DEFAULT 10,
    instructor text,
    image_url text,
    category text DEFAULT 'CLASS',
    credit_cost integer DEFAULT 10,
    coach_image_url text
);

CREATE TABLE IF NOT EXISTS public.registrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    session_id bigint REFERENCES public.sessions(id) ON DELETE CASCADE,
    attended boolean DEFAULT false,
    payer_id uuid REFERENCES public.profiles(id),
    credits_paid integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.availability (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status text CHECK (status IN ('available', 'booked', 'unavailable')) DEFAULT 'available',
    created_at timestamp with time zone DEFAULT now()
);

-- Other tables
CREATE TABLE IF NOT EXISTS public.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    content text,
    image_url text,
    user_id uuid REFERENCES public.profiles(id),
    likes_count integer DEFAULT 0,
    shared_post_id bigint REFERENCES public.posts(id)
);

CREATE TABLE IF NOT EXISTS public.likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid NOT NULL,
    post_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    conversation_id text NOT NULL,
    sender_id uuid NOT NULL,
    content text NOT NULL,
    read boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.players_stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    category text NOT NULL,
    stats jsonb DEFAULT '{}'::jsonb,
    verified boolean DEFAULT false,
    verified_by uuid REFERENCES public.profiles(id),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.voice_commands (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    command_text text NOT NULL,
    action_type text NOT NULL,
    parameters jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);


-- 3. COLUMN PATCHING (Idempotent)

-- PROFILE: Membership Tier
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'membership_tier') THEN
        ALTER TABLE profiles ADD COLUMN membership_tier TEXT CHECK (membership_tier IN ('individual', 'family_2', 'family_3plus')) DEFAULT 'individual';
        UPDATE profiles SET membership_tier = 'individual' WHERE membership_tier IS NULL;
        RAISE NOTICE 'Added membership_tier to profiles';
    END IF;
END $$;

-- PROFILE: Parent ID
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'parent_id') THEN
        ALTER TABLE profiles ADD COLUMN parent_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
        CREATE INDEX IF NOT EXISTS idx_profiles_parent_id ON profiles(parent_id);
    END IF;
END $$;

-- PROFILE: Schedule Photo
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'schedule_photo_url') THEN
        ALTER TABLE profiles ADD COLUMN schedule_photo_url text;
    END IF;
END $$;

-- REGISTRATIONS: Payer ID
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'registrations' AND column_name = 'payer_id') THEN
        ALTER TABLE registrations ADD COLUMN payer_id uuid REFERENCES public.profiles(id);
    END IF;
END $$;

-- REGISTRATIONS: Credits Paid
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'registrations' AND column_name = 'credits_paid') THEN
        ALTER TABLE registrations ADD COLUMN credits_paid integer DEFAULT 0;
    END IF;
END $$;

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_registrations_user_id ON registrations(user_id);
CREATE INDEX IF NOT EXISTS idx_registrations_session_id ON registrations(session_id);
CREATE INDEX IF NOT EXISTS idx_availability_coach_id_time ON availability(coach_id, start_time);
CREATE INDEX IF NOT EXISTS idx_profiles_membership_tier ON profiles(membership_tier);


-- 4. LOGIC & FUNCTIONS (RPCs) - With DROP to handle signature changes

-- TRIGGER: Handle New User
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, first_name, last_name, avatar_url, role, membership_tier)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    new.raw_user_meta_data->>'avatar_url',
    COALESCE(new.raw_user_meta_data->>'role', 'player'),
    'individual'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: BOOK COACH ATOMIC (Updated)
DROP FUNCTION IF EXISTS book_coach_atomic(uuid, uuid, bigint, int, uuid, text);
DROP FUNCTION IF EXISTS book_coach_atomic(uuid, uuid, bigint, int, uuid); 

CREATE OR REPLACE FUNCTION book_coach_atomic(
  p_user_id uuid,
  p_coach_id uuid,
  p_session_id bigint,
  p_credit_cost int,
  p_attendee_id uuid DEFAULT NULL,
  p_origin text DEFAULT 'facilities'
) RETURNS json AS $$
DECLARE
  v_user_credits int;
  v_new_balance int;
  v_final_attendee_id uuid;
BEGIN
  v_final_attendee_id := COALESCE(p_attendee_id, p_user_id);

  PERFORM * FROM availability 
  WHERE coach_id = p_coach_id 
  AND start_time <= (SELECT start_time FROM sessions WHERE id = p_session_id)
  AND end_time >= (SELECT end_time FROM sessions WHERE id = p_session_id)
  FOR UPDATE;
  
  SELECT credits INTO v_user_credits FROM profiles WHERE id = p_user_id;
  IF v_user_credits < p_credit_cost THEN
    RETURN json_build_object('success', false, 'message', 'Insufficient credits.', 'current_balance', v_user_credits);
  END IF;
  
  UPDATE profiles SET credits = credits - p_credit_cost WHERE id = p_user_id RETURNING credits INTO v_new_balance;
  
  INSERT INTO registrations (user_id, session_id, payer_id, credits_paid)
  VALUES (v_final_attendee_id, p_session_id, p_user_id, p_credit_cost);
  
  RETURN json_build_object('success', true, 'message', 'Booking confirmed!', 'new_balance', v_new_balance);
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Booking failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: TRANSFER CREDITS
DROP FUNCTION IF EXISTS transfer_credits(uuid, uuid, int);

CREATE OR REPLACE FUNCTION transfer_credits(
  p_from_user_id uuid,
  p_to_user_id uuid,
  p_amount int
) RETURNS json AS $$
DECLARE
  v_from_credits int;
  v_to_credits int;
  v_parent_id uuid;
BEGIN
  IF p_amount <= 0 THEN RETURN json_build_object('success', false, 'message', 'Transfer amount must be positive'); END IF;

  SELECT credits INTO v_from_credits FROM profiles WHERE id = p_from_user_id;
  IF v_from_credits < p_amount THEN
    RETURN json_build_object('success', false, 'message', 'Insufficient credits');
  END IF;

  SELECT credits, parent_id INTO v_to_credits, v_parent_id FROM profiles WHERE id = p_to_user_id;
  
  IF v_parent_id != p_from_user_id THEN
    RETURN json_build_object('success', false, 'message', 'You can only transfer credits to your own children');
  END IF;

  UPDATE profiles SET credits = credits - p_amount WHERE id = p_from_user_id;
  UPDATE profiles SET credits = credits + p_amount WHERE id = p_to_user_id;

  RETURN json_build_object('success', true, 'message', 'Transfer successful', 'amount', p_amount);
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Transfer failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: CANCEL & REFUND (Exact amount)
DROP FUNCTION IF EXISTS cancel_session_and_refund(uuid, bigint);

CREATE OR REPLACE FUNCTION cancel_session_and_refund(
  p_user_id uuid,
  p_session_id bigint
) RETURNS json AS $$
DECLARE
  v_credits_paid int;
  v_payer_id uuid;
  v_registration_id bigint;
BEGIN
  SELECT id, credits_paid, payer_id INTO v_registration_id, v_credits_paid, v_payer_id
  FROM registrations
  WHERE user_id = p_user_id AND session_id = p_session_id;

  IF v_registration_id IS NULL THEN
    RETURN json_build_object('success', false, 'message', 'Registration not found');
  END IF;

  DELETE FROM registrations WHERE id = v_registration_id;

  IF v_credits_paid > 0 THEN
    UPDATE profiles SET credits = credits + v_credits_paid WHERE id = v_payer_id;
  END IF;

  RETURN json_build_object('success', true, 'message', 'Session cancelled and refunds processed', 'refund_amount', v_credits_paid);
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Cancellation failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC: BOOK SESSION WITH CREDITS (Standard Facility Booking)
DROP FUNCTION IF EXISTS book_session_with_credits(uuid, bigint, uuid);

CREATE OR REPLACE FUNCTION book_session_with_credits(
  p_user_id uuid,
  p_session_id bigint,
  p_attendee_id uuid DEFAULT NULL
) RETURNS json AS $$
DECLARE
  v_credits int;
  v_cost int;
  v_capacity int;
  v_count int;
  v_final_attendee_id uuid;
BEGIN
  v_final_attendee_id := COALESCE(p_attendee_id, p_user_id);

  -- Check capacity
  SELECT max_capacity, credit_cost INTO v_capacity, v_cost FROM sessions WHERE id = p_session_id;
  SELECT count(*) INTO v_count FROM registrations WHERE session_id = p_session_id;
  
  IF v_count >= v_capacity THEN
    RETURN json_build_object('success', false, 'message', 'Session is full');
  END IF;

  -- Check credits
  SELECT credits INTO v_credits FROM profiles WHERE id = p_user_id;
  IF v_credits < v_cost THEN
    RETURN json_build_object('success', false, 'message', 'Insufficient credits');
  END IF;

  -- Transact
  UPDATE profiles SET credits = credits - v_cost WHERE id = p_user_id;
  INSERT INTO registrations (user_id, session_id, payer_id, credits_paid)
  VALUES (v_final_attendee_id, p_session_id, p_user_id, v_cost);

  RETURN json_build_object('success', true, 'message', 'Booked successfully');
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'message', 'Error: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 5. DATA PATCHES (Safe to run multiple times)

UPDATE sessions SET credit_cost = 200 WHERE title IN ('Golf Simulator - North Bay', 'Golf Simulator - South Bay');
UPDATE sessions SET credit_cost = 100 WHERE title IN ('Shooting Bay - Blue Pad', 'Shooting Bay - Green Pad');
UPDATE sessions SET credit_cost = 850 WHERE title LIKE 'Shooting (Senior)%';
UPDATE sessions SET credit_cost = 500 WHERE title LIKE 'Shooting (Junior)%';
UPDATE sessions SET credit_cost = 700 WHERE title = 'Personal Training';
UPDATE sessions SET credit_cost = 1100 WHERE title LIKE 'Golf Lesson%';

-- 6. PERMISSIONS & GRANTS
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO service_role;

GRANT SELECT ON public.profiles TO authenticated;
GRANT SELECT ON public.sessions TO authenticated;
GRANT SELECT ON public.availability TO authenticated;

-- Explicitly allow Authenticated users to call RPCs
-- This ensures that re-creating the functions didn't strip permissions
GRANT EXECUTE ON FUNCTION book_coach_atomic TO authenticated;
GRANT EXECUTE ON FUNCTION transfer_credits TO authenticated;
GRANT EXECUTE ON FUNCTION cancel_session_and_refund TO authenticated;
GRANT EXECUTE ON FUNCTION book_session_with_credits TO authenticated;
