import { Pool } from 'pg';
import * as dotenv from 'dotenv';
import path from 'path';

// Load .env.local
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

async function runMigration() {
    console.log('Running metrics migration...');

    if (!process.env.DATABASE_URL) {
        console.error('DATABASE_URL is not set in .env.local');
        process.exit(1);
    }

    const pool = new Pool({
        connectionString: process.env.DATABASE_URL
    });

    try {
        await pool.query('BEGIN');

        console.log('Creating booking_cancellations table...');
        await pool.query(`
            CREATE TABLE IF NOT EXISTS public.booking_cancellations (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
                session_id bigint REFERENCES public.sessions(id) ON DELETE SET NULL,
                refunded_credits integer DEFAULT 0,
                created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
            );

            ALTER TABLE public.booking_cancellations ENABLE ROW LEVEL SECURITY;
            GRANT ALL ON TABLE public.booking_cancellations TO service_role;
        `);

        console.log('Updating cancel_session_and_refund function...');
        await pool.query(`
            create or replace function cancel_session_and_refund(
              p_attendee_id uuid,
              p_session_id bigint
            )
            returns json
            language plpgsql
            security definer
            as $$
            declare
              v_credit_cost int;
              v_payer_id uuid;
            begin
              -- Check registration and get Payer
              SELECT payer_id INTO v_payer_id 
              FROM registrations 
              WHERE user_id = p_attendee_id AND session_id = p_session_id;

              if not found then
                return json_build_object('success', false, 'message', 'Booking not found.');
              end if;

              -- Default payer to attendee if null
              v_payer_id := COALESCE(v_payer_id, p_attendee_id);

              select credit_cost into v_credit_cost from sessions where id = p_session_id;

              if v_credit_cost is null then
                insert into booking_cancellations (user_id, session_id, refunded_credits) values (p_attendee_id, p_session_id, 0);
                delete from registrations where user_id = p_attendee_id and session_id = p_session_id;
                return json_build_object('success', true, 'message', 'Cancellation confirmed.');
              end if;

              -- Refund PAYER
              update profiles set credits = credits + v_credit_cost where id = v_payer_id;
              
              -- Log Cancellation
              insert into booking_cancellations (user_id, session_id, refunded_credits) values (p_attendee_id, p_session_id, v_credit_cost);
              
              delete from registrations where user_id = p_attendee_id and session_id = p_session_id;

              return json_build_object('success', true, 'message', 'Cancellation successful. Credits refunded.', 'refund_amount', v_credit_cost);
            end;
            $$;
        `);

        await pool.query('COMMIT');
        console.log('✅ Metrics migration completed successfully!');
    } catch (error: any) {
        await pool.query('ROLLBACK');
        console.error('Migration failed:', error.message);
        process.exit(1);
    } finally {
        await pool.end();
    }
}

runMigration();
