import { Client } from 'pg';

const dbUrl = process.env.DATABASE_URL || process.env.JRDUCKS_DATABASE_URL;

const JRDUCKS_DB_CONFIG = dbUrl ? {
  connectionString: dbUrl,
  ssl: { rejectUnauthorized: false }
} : {
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432', 10),
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME || 'postgres',
  ssl: { rejectUnauthorized: false }
};

const MIGRATION_SQL = `
-- ============================================================================
-- ANAHEIM JR. DUCKS / WHITELABEL PRODUCTION SCHEMA BUNDLE
-- Target: Supabase Postgres 17.6 (hzltndrltyseifwbmjeg)
-- ============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. CORE TABLES

-- PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name text,
    last_name text,
    username text,
    role text CHECK (role IN ('player', 'coach', 'parent', 'admin', 'sys-admin')) DEFAULT 'player',
    credits integer DEFAULT 0,
    team text,
    position text,
    avatar_url text,
    bio text,
    created_at timestamp with time zone DEFAULT now(),
    parent_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    contact_email text,
    mobile text,
    phone text,
    emergency_contact text,
    schedule_photo_url text,
    intro_video_url text,
    preferences jsonb DEFAULT '{}'::jsonb,
    gallery_images text[] DEFAULT '{}'::text[],
    tier text CHECK (tier IN ('free', 'individual', 'family_2', 'family_3plus')) DEFAULT 'free',
    membership_tier text CHECK (membership_tier IN ('individual', 'family_2', 'family_3plus')) DEFAULT 'individual',
    stripe_customer_id text,
    stripe_subscription_id text,
    subscription_status text DEFAULT 'inactive',
    account_status text DEFAULT 'inactive',
    membership_start timestamp with time zone,
    membership_expires timestamp with time zone,
    membership_history jsonb DEFAULT '[]'::jsonb
);

-- SESSIONS
CREATE TABLE IF NOT EXISTS public.sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    description text,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    max_capacity integer DEFAULT 10,
    instructor text,
    image_url text,
    coach_image_url text,
    category text DEFAULT 'CLASS',
    credit_cost integer DEFAULT 10,
    session_type_id text,
    priority integer DEFAULT 0,
    bay_number integer,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- REGISTRATIONS
CREATE TABLE IF NOT EXISTS public.registrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    registered_at timestamp with time zone DEFAULT now(),
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    session_id bigint REFERENCES public.sessions(id) ON DELETE CASCADE,
    attended boolean DEFAULT false,
    payer_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    credits_paid integer DEFAULT 0,
    status text DEFAULT 'registered',
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    CONSTRAINT uq_registrations_user_session UNIQUE (user_id, session_id)
);

-- AVAILABILITY
CREATE TABLE IF NOT EXISTS public.availability (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status text CHECK (status IN ('available', 'booked', 'unavailable')) DEFAULT 'available',
    created_at timestamp with time zone DEFAULT now()
);

-- SESSION TYPES
CREATE TABLE IF NOT EXISTS public.session_types (
    id text PRIMARY KEY,
    title text NOT NULL,
    category text NOT NULL,
    description text,
    image_url text,
    credit_cost integer DEFAULT 10,
    created_at timestamp with time zone DEFAULT now()
);

-- COACH SERVICES
CREATE TABLE IF NOT EXISTS public.coach_services (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    service_type_id text REFERENCES public.session_types(id) ON DELETE CASCADE,
    tier text DEFAULT 'junior',
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(coach_id, service_type_id)
);

-- TRANSACTIONS
CREATE TABLE IF NOT EXISTS public.transactions (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount integer NOT NULL,
    type text NOT NULL CHECK (type IN ('topup', 'membership', 'transfer', 'booking', 'refund')),
    session_id bigint REFERENCES public.sessions(id) ON DELETE SET NULL,
    stripe_session_id text UNIQUE, 
    description text,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- TEAMS
CREATE TABLE IF NOT EXISTS public.teams (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- TEAM MEMBERS
CREATE TABLE IF NOT EXISTS public.team_members (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    team_id uuid REFERENCES public.teams(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    joined_at timestamp with time zone DEFAULT now(),
    UNIQUE(team_id, user_id)
);

-- POSTS & COMMUNITY
CREATE TABLE IF NOT EXISTS public.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    content text,
    image_url text,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    likes_count integer DEFAULT 0,
    shared_post_id bigint REFERENCES public.posts(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    UNIQUE(user_id, post_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    conversation_id text NOT NULL,
    sender_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content text NOT NULL,
    read boolean DEFAULT false,
    team_id uuid REFERENCES public.teams(id) ON DELETE CASCADE
);

-- PLAYERS STATS
CREATE TABLE IF NOT EXISTS public.players_stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    category text NOT NULL,
    stats jsonb DEFAULT '{}'::jsonb,
    verified boolean DEFAULT false,
    verified_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    updated_at timestamp with time zone DEFAULT now()
);

-- VOICE COMMANDS
CREATE TABLE IF NOT EXISTS public.voice_commands (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    command_text text NOT NULL,
    action_type text NOT NULL,
    parameters jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

-- PLAYER RELATIONSHIPS (PARENT/CHILD)
CREATE TABLE IF NOT EXISTS public.player_relationships (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    parent_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    child_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    relationship_type varchar(50) DEFAULT 'parent_child',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

-- DRILL HUB & TRAINING
CREATE TABLE IF NOT EXISTS public.coach_drills (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    title text NOT NULL,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    age_tags text[] DEFAULT '{}'::text[],
    level_tags text[] DEFAULT '{}'::text[],
    group_tags text[] DEFAULT '{}'::text[],
    skill_tags text[] DEFAULT '{}'::text[],
    status text DEFAULT 'published',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.coach_drill_steps (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    drill_id uuid REFERENCES public.coach_drills(id) ON DELETE CASCADE,
    step_number integer NOT NULL,
    title text,
    instruction text NOT NULL,
    diagram_url text,
    video_url text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.training_plans (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.training_plan_drills (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    plan_id uuid REFERENCES public.training_plans(id) ON DELETE CASCADE,
    drill_id uuid REFERENCES public.coach_drills(id) ON DELETE CASCADE,
    order_index integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

-- CHECK INS (QR CODE)
CREATE TABLE IF NOT EXISTS public.check_ins (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    location_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- ANNOUNCEMENTS (NEWS & EVENTS)
CREATE TABLE IF NOT EXISTS public.announcements (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title text NOT NULL,
    content text NOT NULL,
    type text NOT NULL CHECK (type IN ('news', 'event')),
    published boolean DEFAULT true,
    event_date timestamp with time zone,
    image_url text,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- COACH NOTES
CREATE TABLE IF NOT EXISTS public.coach_notes (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    player_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. INDEXES
CREATE INDEX IF NOT EXISTS idx_registrations_user_id ON public.registrations(user_id);
CREATE INDEX IF NOT EXISTS idx_registrations_session_id ON public.registrations(session_id);
CREATE INDEX IF NOT EXISTS idx_availability_coach_id_time ON public.availability(coach_id, start_time);
CREATE INDEX IF NOT EXISTS idx_profiles_membership_tier ON public.profiles(membership_tier);
CREATE INDEX IF NOT EXISTS idx_profiles_stripe_customer_id ON public.profiles(stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_profiles_parent_id ON public.profiles(parent_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_announcements_published ON public.announcements(published, created_at DESC);

-- 4. RPC FUNCTIONS

-- INCREMENT CREDITS
CREATE OR REPLACE FUNCTION public.increment_credits(p_user_id UUID, p_amount INT)
RETURNS VOID AS $$
BEGIN
    UPDATE public.profiles
    SET credits = COALESCE(credits, 0) + p_amount
    WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- BOOK SESSION WITH CREDITS
CREATE OR REPLACE FUNCTION public.book_session_with_credits(
    p_user_id uuid,
    p_session_id bigint,
    p_attendee_id uuid DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_credit_cost int;
    v_user_credits int;
    v_sub_status text;
    v_final_attendee_id uuid;
    v_new_balance int;
BEGIN
    v_final_attendee_id := COALESCE(p_attendee_id, p_user_id);

    SELECT credit_cost INTO v_credit_cost FROM public.sessions WHERE id = p_session_id;
    SELECT credits, subscription_status INTO v_user_credits, v_sub_status 
    FROM public.profiles WHERE id = p_user_id;

    IF v_credit_cost IS NULL THEN
        RETURN json_build_object('success', false, 'message', 'Session cost not defined.');
    END IF;

    IF v_sub_status IS NULL OR (v_sub_status != 'active' AND v_sub_status != 'trialing') THEN
        RETURN json_build_object('success', false, 'message', 'Membership dormant. Renew to unlock credits.');
    END IF;

    IF v_user_credits < v_credit_cost THEN
        RETURN json_build_object('success', false, 'message', 'Insufficient credits.');
    END IF;

    UPDATE public.profiles SET credits = credits - v_credit_cost WHERE id = p_user_id
    RETURNING credits INTO v_new_balance;
    
    INSERT INTO public.registrations (user_id, session_id, payer_id, credits_paid) 
    VALUES (v_final_attendee_id, p_session_id, p_user_id, v_credit_cost)
    ON CONFLICT (user_id, session_id) DO UPDATE SET
        status = 'registered',
        credits_paid = EXCLUDED.credits_paid,
        payer_id = EXCLUDED.payer_id,
        registered_at = now();

    RETURN json_build_object('success', true, 'message', 'Booking confirmed!', 'new_balance', v_new_balance);
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Booking failed: ' || SQLERRM);
END;
$$;

-- BOOK COACH ATOMIC
CREATE OR REPLACE FUNCTION public.book_coach_atomic(
    p_user_id uuid,
    p_coach_id uuid,
    p_session_id bigint,
    p_credit_cost int,
    p_attendee_id uuid DEFAULT NULL,
    p_origin text DEFAULT 'facilities'
) RETURNS json AS $$
DECLARE
    v_user_credits int;
    v_new_balance int;
    v_final_attendee_id uuid;
BEGIN
    v_final_attendee_id := COALESCE(p_attendee_id, p_user_id);

    PERFORM * FROM public.availability 
    WHERE coach_id = p_coach_id 
    AND start_time <= (SELECT start_time FROM public.sessions WHERE id = p_session_id)
    AND end_time >= (SELECT end_time FROM public.sessions WHERE id = p_session_id)
    FOR UPDATE;
    
    SELECT credits INTO v_user_credits FROM public.profiles WHERE id = p_user_id;
    
    IF v_user_credits < p_credit_cost THEN
        RETURN json_build_object('success', false, 'message', 'Insufficient credits.', 'current_balance', v_user_credits);
    END IF;
    
    UPDATE public.profiles SET credits = credits - p_credit_cost WHERE id = p_user_id RETURNING credits INTO v_new_balance;
    
    INSERT INTO public.registrations (user_id, session_id, payer_id, credits_paid)
    VALUES (v_final_attendee_id, p_session_id, p_user_id, p_credit_cost)
    ON CONFLICT (user_id, session_id) DO UPDATE SET
        status = 'registered',
        credits_paid = EXCLUDED.credits_paid,
        payer_id = EXCLUDED.payer_id,
        registered_at = now();
    
    RETURN json_build_object('success', true, 'message', 'Booking confirmed!', 'new_balance', v_new_balance);
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Booking failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- CANCEL SESSION AND REFUND
CREATE OR REPLACE FUNCTION public.cancel_session_and_refund(
    p_user_id uuid,
    p_session_id bigint
) RETURNS json AS $$
DECLARE
    v_credits_paid int;
    v_payer_id uuid;
    v_registration_id bigint;
BEGIN
    SELECT id, credits_paid, payer_id INTO v_registration_id, v_credits_paid, v_payer_id
    FROM public.registrations
    WHERE user_id = p_user_id AND session_id = p_session_id;

    IF v_registration_id IS NULL THEN
        RETURN json_build_object('success', false, 'message', 'Registration not found');
    END IF;

    DELETE FROM public.registrations WHERE id = v_registration_id;

    IF v_credits_paid > 0 THEN
        UPDATE public.profiles SET credits = credits + v_credits_paid WHERE id = COALESCE(v_payer_id, p_user_id);
    END IF;

    RETURN json_build_object('success', true, 'message', 'Session cancelled and refunds processed', 'refund_amount', v_credits_paid);
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Cancellation failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- MASTER BOOK ATOMIC (Production Master)
CREATE OR REPLACE FUNCTION public.master_book_atomic(
  p_user_id UUID,
  p_session_id BIGINT,
  p_attendee_ids UUID[],
  p_coach_id UUID DEFAULT NULL,
  p_coach_tier TEXT DEFAULT 'junior',
  p_origin TEXT DEFAULT 'facilities',
  p_created_by UUID DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_main_session_start TIMESTAMPTZ;
  v_main_session_end TIMESTAMPTZ;
  v_main_session_title TEXT;
  v_main_session_cost INT;
  v_max_capacity INT;
  v_current_bookings INT;
  
  v_coach_first_name TEXT;
  v_coach_last_name TEXT;
  v_coach_avatar TEXT;
  v_coach_cost INT;
  v_coach_session_id BIGINT;
  
  v_total_cost INT;
  v_user_credits INT;
  v_user_sub_status TEXT;
  v_user_acc_status TEXT;
  v_membership_expires TIMESTAMPTZ;
  v_parent_id UUID;
  
  v_attendee_id UUID;
  v_coach_available BOOLEAN;
  v_results JSONB := '[]'::JSONB;
BEGIN
  -- 1. LOCK USER PROFILE
  SELECT 
    credits, subscription_status, account_status, membership_expires, parent_id 
  INTO 
    v_user_credits, v_user_sub_status, v_user_acc_status, v_membership_expires, v_parent_id
  FROM public.profiles 
  WHERE id = p_user_id 
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', 'User profile not found');
  END IF;

  -- 2. HANDLE CHILD ACCOUNTS (Fetch membership from parent)
  IF v_parent_id IS NOT NULL THEN
    SELECT 
      subscription_status, account_status, membership_expires
    INTO 
      v_user_sub_status, v_user_acc_status, v_membership_expires
    FROM public.profiles 
    WHERE id = v_parent_id;
  END IF;

  -- 3. CHECK ACCOUNT STATUS (ENFORCED MEMBERSHIP)
  IF (v_user_sub_status IS NULL OR v_user_sub_status NOT IN ('active', 'trialing'))
     AND (v_membership_expires IS NULL OR v_membership_expires < NOW()) THEN
    RETURN jsonb_build_object(
      'success', false, 
      'message', 'Account Locked: Active membership required to book. Please purchase a membership or contact support.', 
      'code', 'SUBSCRIPTION_LOCKED'
    );
  END IF;

  -- 4. FETCH MAIN SESSION DATA
  SELECT 
    start_time, end_time, title, credit_cost, max_capacity 
  INTO 
    v_main_session_start, v_main_session_end, v_main_session_title, v_main_session_cost, v_max_capacity
  FROM public.sessions 
  WHERE id = p_session_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', 'Main session not found');
  END IF;

  -- 5. CALCULATE TOTAL COSTS
  v_coach_cost := CASE 
    WHEN p_coach_tier = 'senior' THEN 850
    WHEN p_coach_tier = 'junior' THEN 500
    WHEN p_coach_tier = 'pt' THEN 700
    ELSE 600
  END;

  v_total_cost := 0;
  
  IF p_origin = 'facilities' OR (p_origin = 'coaches' AND p_coach_id IS NULL) THEN
    v_total_cost := v_total_cost + (v_main_session_cost * array_length(p_attendee_ids, 1));
  END IF;
  
  IF p_coach_id IS NOT NULL THEN
    v_total_cost := v_total_cost + (v_coach_cost * array_length(p_attendee_ids, 1));
  END IF;

  -- 6. CHECK CREDITS
  IF v_user_credits < v_total_cost THEN
    RETURN jsonb_build_object('success', false, 'message', 'Insufficient credits. Required: ' || v_total_cost || ', Available: ' || v_user_credits, 'code', 'INSUFFICIENT_CREDITS');
  END IF;

  -- 7. CHECK CAPACITY
  SELECT count(*) INTO v_current_bookings FROM public.registrations WHERE session_id = p_session_id AND status != 'cancelled';
  IF v_current_bookings + array_length(p_attendee_ids, 1) > v_max_capacity THEN
    RETURN jsonb_build_object('success', false, 'message', 'Capacity met', 'code', 'CAPACITY_MET');
  END IF;

  -- 8. CHECK COACH AVAILABILITY
  IF p_coach_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.availability 
      WHERE coach_id = p_coach_id 
      AND start_time <= v_main_session_start 
      AND end_time >= v_main_session_end
    ) INTO v_coach_available;

    IF NOT v_coach_available THEN
      RETURN jsonb_build_object('success', false, 'message', 'Coach not available at this time');
    END IF;

    SELECT first_name, last_name, avatar_url INTO v_coach_first_name, v_coach_last_name, v_coach_avatar
    FROM public.profiles WHERE id = p_coach_id;

    INSERT INTO public.sessions (
      title, category, instructor, start_time, end_time, credit_cost, description, coach_image_url
    ) VALUES (
      'Private with ' || v_coach_first_name,
      'PRIVATE',
      TRIM(v_coach_first_name || ' ' || COALESCE(v_coach_last_name, '')),
      v_main_session_start,
      v_main_session_end,
      v_coach_cost,
      'Private coaching during ' || v_main_session_title,
      v_coach_avatar
    ) RETURNING id INTO v_coach_session_id;
  END IF;

  -- 9. EXECUTE BOOKINGS
  FOREACH v_attendee_id IN ARRAY p_attendee_ids LOOP
    IF p_origin = 'facilities' OR (p_origin = 'coaches' AND p_coach_id IS NULL) THEN
      INSERT INTO public.registrations (session_id, user_id, payer_id, credits_paid, created_by)
      VALUES (p_session_id, v_attendee_id, p_user_id, v_main_session_cost, p_created_by)
      ON CONFLICT (user_id, session_id) 
      DO UPDATE SET 
        status = 'registered',
        payer_id = EXCLUDED.payer_id,
        credits_paid = EXCLUDED.credits_paid,
        created_by = EXCLUDED.created_by,
        registered_at = NOW();
      
      v_results := v_results || jsonb_build_object('attendeeId', v_attendee_id, 'type', 'facility', 'success', true);
    END IF;

    IF v_coach_session_id IS NOT NULL THEN
      INSERT INTO public.registrations (session_id, user_id, payer_id, credits_paid, created_by)
      VALUES (v_coach_session_id, v_attendee_id, p_user_id, v_coach_cost, p_created_by)
      ON CONFLICT (user_id, session_id) 
      DO UPDATE SET 
        status = 'registered',
        payer_id = EXCLUDED.payer_id,
        credits_paid = EXCLUDED.credits_paid,
        created_by = EXCLUDED.created_by,
        registered_at = NOW();
      
      v_results := v_results || jsonb_build_object('attendeeId', v_attendee_id, 'type', 'coach', 'success', true);
    END IF;
  END LOOP;

  -- 10. DEDUCT TOTAL CREDITS
  UPDATE public.profiles 
  SET credits = credits - v_total_cost 
  WHERE id = p_user_id;

  -- 11. LOG TRANSACTION
  INSERT INTO public.transactions (user_id, amount, type, session_id, description, created_by)
  VALUES (p_user_id, -v_total_cost, 'booking', p_session_id, 'Booking for ' || v_main_session_title || ' (' || array_length(p_attendee_ids, 1) || ' attendees)', p_created_by);

  RETURN jsonb_build_object('success', true, 'message', 'Booking successful', 'results', v_results);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- TRANSFER CREDITS
CREATE OR REPLACE FUNCTION public.transfer_credits(
    p_from_user_id uuid,
    p_to_user_id uuid,
    p_amount int
) RETURNS json AS $$
DECLARE
    v_from_credits int;
    v_to_credits int;
    v_parent_id uuid;
BEGIN
    IF p_amount <= 0 THEN 
        RETURN json_build_object('success', false, 'message', 'Transfer amount must be positive'); 
    END IF;

    SELECT credits INTO v_from_credits FROM public.profiles WHERE id = p_from_user_id;
    
    IF v_from_credits < p_amount THEN
        RETURN json_build_object('success', false, 'message', 'Insufficient credits');
    END IF;

    SELECT credits, parent_id INTO v_to_credits, v_parent_id FROM public.profiles WHERE id = p_to_user_id;
    
    IF v_parent_id != p_from_user_id THEN
        RETURN json_build_object('success', false, 'message', 'You can only transfer credits to your own children');
    END IF;

    UPDATE public.profiles SET credits = credits - p_amount WHERE id = p_from_user_id;
    UPDATE public.profiles SET credits = credits + p_amount WHERE id = p_to_user_id;

    RETURN json_build_object('success', true, 'message', 'Transfer successful', 'amount', p_amount);
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Transfer failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- HANDLE NEW USER (TRIGGER)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.profiles (
        id,
        first_name,
        last_name,
        avatar_url,
        role,
        membership_tier,
        contact_email
    )
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'first_name', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'last_name', ''),
        COALESCE(new.raw_user_meta_data->>'avatar_url', 'https://placehold.co/100'),
        COALESCE(new.raw_user_meta_data->>'role', 'player'),
        'individual',
        new.email
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_drills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_drill_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_plan_drills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_ins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_notes ENABLE ROW LEVEL SECURITY;

-- POLICIES
DROP POLICY IF EXISTS "profiles_public_read" ON public.profiles;
CREATE POLICY "profiles_public_read" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "profiles_own_update" ON public.profiles;
CREATE POLICY "profiles_own_update" ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "sessions_public_read" ON public.sessions;
CREATE POLICY "sessions_public_read" ON public.sessions FOR SELECT USING (true);

DROP POLICY IF EXISTS "session_types_public_read" ON public.session_types;
CREATE POLICY "session_types_public_read" ON public.session_types FOR SELECT USING (true);

DROP POLICY IF EXISTS "availability_public_read" ON public.availability;
CREATE POLICY "availability_public_read" ON public.availability FOR SELECT USING (true);

DROP POLICY IF EXISTS "registrations_own_read" ON public.registrations;
CREATE POLICY "registrations_own_read" ON public.registrations FOR SELECT USING (auth.uid() = user_id OR auth.uid() = payer_id);

DROP POLICY IF EXISTS "transactions_own_read" ON public.transactions;
CREATE POLICY "transactions_own_read" ON public.transactions FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "announcements_public_read" ON public.announcements;
CREATE POLICY "announcements_public_read" ON public.announcements FOR SELECT USING (published = true);

DROP POLICY IF EXISTS "posts_public_read" ON public.posts;
CREATE POLICY "posts_public_read" ON public.posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "likes_public_read" ON public.likes;
CREATE POLICY "likes_public_read" ON public.likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "checkins_own_read" ON public.check_ins;
CREATE POLICY "checkins_own_read" ON public.check_ins FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "teams_public_read" ON public.teams;
CREATE POLICY "teams_public_read" ON public.teams FOR SELECT USING (true);

DROP POLICY IF EXISTS "drills_public_read" ON public.coach_drills;
CREATE POLICY "drills_public_read" ON public.coach_drills FOR SELECT USING (true);

-- 6. PERMISSIONS & GRANTS
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

GRANT SELECT ON public.profiles TO authenticated, anon;
GRANT SELECT ON public.sessions TO authenticated, anon;
GRANT SELECT ON public.session_types TO authenticated, anon;
GRANT SELECT ON public.availability TO authenticated, anon;
GRANT SELECT ON public.announcements TO authenticated, anon;
GRANT SELECT ON public.posts TO authenticated, anon;
GRANT SELECT ON public.likes TO authenticated, anon;
GRANT SELECT ON public.teams TO authenticated, anon;
GRANT SELECT ON public.coach_drills TO authenticated, anon;
GRANT SELECT ON public.coach_drill_steps TO authenticated, anon;
GRANT SELECT ON public.training_plans TO authenticated, anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.registrations TO authenticated;
GRANT SELECT, INSERT ON public.transactions TO authenticated;
GRANT SELECT, INSERT ON public.check_ins TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.posts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.likes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.messages TO authenticated;

GRANT EXECUTE ON FUNCTION public.book_coach_atomic TO authenticated;
GRANT EXECUTE ON FUNCTION public.transfer_credits TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_session_and_refund TO authenticated;
GRANT EXECUTE ON FUNCTION public.book_session_with_credits TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_credits TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.master_book_atomic TO authenticated, service_role;

-- 7. SEED INITIAL CORE SESSION TYPES (Jr Ducks Hockey Specific)
INSERT INTO public.session_types (id, title, category, credit_cost, description, image_url)
VALUES 
  ('hockey-skills', 'Hockey Skills & Power Skating', 'CLASS', 10, 'High-tempo edge work, power skating, and shooting precision clinic.', 'https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?w=800'),
  ('goalie-clinic', 'Elite Goaltending Clinic', 'CLASS', 15, 'Angles, depth, rebound control, and recovery movement drills.', 'https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?w=800'),
  ('private-ice', 'Private 1-on-1 Coaching', 'PRIVATE', 20, 'Tailored 1-on-1 coaching focusing on player biomechanics and skill mastery.', 'https://images.unsplash.com/photo-1544367563-12123d832e30?w=800'),
  ('synthetic-ice-bay', 'Shooting Bay & Treadmill', 'FACILITY', 8, 'Dedicated rapid-fire shooting bay and skating treadmill lane.', 'https://images.unsplash.com/photo-1515523110800-9415d13b84a8?w=800')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  credit_cost = EXCLUDED.credit_cost,
  description = EXCLUDED.description;

-- 8. SEED WELCOME ANNOUNCEMENT
INSERT INTO public.announcements (title, content, type, published, image_url)
SELECT 
  'Welcome to the Anaheim Jr. Ducks Portal!',
  'Welcome to our dedicated Anaheim Jr. Ducks digital training and development portal. Book your ice times, sync your schedules, and track your athletic progression directly from your dashboard.',
  'news',
  true,
  'https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?w=800'
WHERE NOT EXISTS (
  SELECT 1 FROM public.announcements WHERE title = 'Welcome to the Anaheim Jr. Ducks Portal!'
);

-- NOTIFY SCHEMA RELOAD
NOTIFY pgrst, 'reload schema';
`;

async function runMigration() {
  console.log('🚀 Starting Full Migration for Jr Ducks Supabase DB...');
  console.log('Host:', JRDUCKS_DB_CONFIG.host);
  const client = new Client(JRDUCKS_DB_CONFIG);

  try {
    await client.connect();
    console.log('🔌 Connected to database.');

    console.log('⏳ Executing DDL migration bundle...');
    await client.query(MIGRATION_SQL);
    console.log('✅ DDL migration bundle applied successfully!');

    // Verify all created tables
    const tablesRes = await client.query(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      ORDER BY table_name;
    `);
    console.log(`\n📊 Verified ${tablesRes.rows.length} Public Tables:`);
    tablesRes.rows.forEach(r => console.log(`   - ${r.table_name}`));

    // Verify RPC functions
    const rpcRes = await client.query(`
      SELECT routine_name 
      FROM information_schema.routines 
      WHERE routine_schema = 'public'
      ORDER BY routine_name;
    `);
    console.log(`\n⚡ Verified ${rpcRes.rows.length} RPC Functions:`);
    rpcRes.rows.forEach(r => console.log(`   - ${r.routine_name}`));

    // Check session types seed
    const stRes = await client.query('SELECT id, title, category, credit_cost FROM public.session_types;');
    console.log('\n🏒 Seeded Session Types:');
    stRes.rows.forEach(r => console.log(`   - [${r.category}] ${r.title} (${r.credit_cost} credits)`));

    // Check announcements seed
    const anRes = await client.query('SELECT title, type, published FROM public.announcements;');
    console.log('\n📢 Seeded Announcements:');
    anRes.rows.forEach(r => console.log(`   - [${r.type}] ${r.title} (Published: ${r.published})`));

    console.log('\n🎉 ALL MIGRATIONS AND VERIFICATIONS COMPLETED SUCCESSFULLY!');
  } catch (err: any) {
    console.error('❌ Migration Failed:', err.message);
    if (err.position) {
      console.error('Position:', err.position);
    }
    process.exit(1);
  } finally {
    await client.end();
  }
}

runMigration();
