-- ============================================================================
-- EAST APP HK - PRODUCTION DEPLOYMENT BUNDLE
-- Generated by Antigravity
-- ============================================================================
-- INSTRUCTIONS:
-- 1. Open your Supabase Project Dashboard
-- 2. Go to SQL Editor
-- 3. Paste this entire file
-- 4. Click RUN
-- ============================================================================

-- 1. BASE EXTENSIONS & SETTINGS
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

-- 2. TABLES & SEQUENCE DEFINITIONS

CREATE TABLE IF NOT EXISTS "public"."availability" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "coach_id" "uuid",
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "is_recurring" boolean DEFAULT false,
    "status" "text" DEFAULT 'available'::"text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);

CREATE TABLE IF NOT EXISTS "public"."likes" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "post_id" bigint
);
ALTER TABLE "public"."likes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."likes_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint NOT NULL,
    "sender_id" "uuid",
    "receiver_id" "uuid",
    "content" "text",
    "image_url" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "shared_event_id" bigint
);
ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."player_relationships" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "parent_id" "uuid",
    "child_id" "uuid",
    "relationship_type" character varying(50) DEFAULT 'parent_child'::character varying,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "public"."players_stats" (
    "id" bigint NOT NULL,
    "player_id" "uuid",
    "age" integer,
    "season" integer,
    "team" "text",
    "games_played_season" integer,
    "games_played_total" integer,
    "games_missed_healthy" integer,
    "games_missed_injured" integer,
    "goals_season" integer,
    "goals_total" integer,
    "assists_season" integer,
    "assists_total" integer,
    "gp" integer,
    "points" integer,
    "gwg" integer,
    "ppg" integer,
    "shg" integer,
    "pim" integer,
    "top_scorer_team" boolean,
    "top_scorer_league" boolean,
    "least_pim_team" boolean,
    "most_shots_team" boolean,
    "is_verified" boolean DEFAULT false,
    "verified_by" "uuid",
    "verified_at" timestamp with time zone,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "public"."players_stats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."players_stats_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."posts" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "image_url" "text",
    "caption" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "shared_post_id" bigint
);
ALTER TABLE "public"."posts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."posts_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "username" "text",
    "first_name" "text",
    "last_name" "text",
    "mobile" "text",
    "contact_email" "text",
    "avatar_url" "text",
    "bio" "text",
    "tier" "text" DEFAULT 'free'::"text",
    "stripe_customer_id" "text",
    "stripe_subscription_id" "text",
    "subscription_status" "text" DEFAULT 'inactive'::"text",
    "credits" integer DEFAULT 100,
    "gallery_images" "text"[] DEFAULT '{}'::"text"[],
    "schedule_photo_url" "text",
    "role" "text" DEFAULT 'player'::"text",
    "parent_id" "uuid",
    "intro_video_url" "text",
    "preferences" "jsonb" DEFAULT '{}'::"jsonb",
    "team" "text",
    "position" "text",
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS "public"."registrations" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "session_id" bigint NOT NULL,
    "registered_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);
ALTER TABLE "public"."registrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."registrations_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."sessions" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "category" "text",
    "instructor" "text",
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "image_url" "text",
    "coach_image_url" "text",
    "description" "text",
    "credit_cost" integer DEFAULT 10
);
ALTER TABLE "public"."sessions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sessions_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."voice_commands" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "coach_id" "uuid",
    "command_text" "text" NOT NULL,
    "processed_json" "jsonb",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);

-- 3. CONSTRAINTS & FOREIGN KEYS

ALTER TABLE ONLY "public"."availability" ADD CONSTRAINT "availability_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."likes" ADD CONSTRAINT "likes_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."likes" ADD CONSTRAINT "likes_user_id_post_id_key" UNIQUE ("user_id", "post_id");
ALTER TABLE ONLY "public"."messages" ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."player_relationships" ADD CONSTRAINT "player_relationships_parent_id_child_id_key" UNIQUE ("parent_id", "child_id");
ALTER TABLE ONLY "public"."player_relationships" ADD CONSTRAINT "player_relationships_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."players_stats" ADD CONSTRAINT "players_stats_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."posts" ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."registrations" ADD CONSTRAINT "registrations_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."registrations" ADD CONSTRAINT "registrations_user_id_session_id_key" UNIQUE ("user_id", "session_id");
ALTER TABLE ONLY "public"."sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."voice_commands" ADD CONSTRAINT "voice_commands_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."availability" ADD CONSTRAINT "availability_coach_id_fkey" FOREIGN KEY ("coach_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."likes" ADD CONSTRAINT "likes_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id");
ALTER TABLE ONLY "public"."likes" ADD CONSTRAINT "likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");
ALTER TABLE ONLY "public"."player_relationships" ADD CONSTRAINT "player_relationships_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."players_stats" ADD CONSTRAINT "players_stats_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."players_stats" ADD CONSTRAINT "players_stats_verified_by_fkey" FOREIGN KEY ("verified_by") REFERENCES "public"."profiles"("id");
ALTER TABLE ONLY "public"."posts" ADD CONSTRAINT "posts_shared_post_id_fkey" FOREIGN KEY ("shared_post_id") REFERENCES "public"."posts"("id");
ALTER TABLE ONLY "public"."posts" ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profiles_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."registrations" ADD CONSTRAINT "registrations_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."registrations" ADD CONSTRAINT "registrations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."voice_commands" ADD CONSTRAINT "voice_commands_coach_id_fkey" FOREIGN KEY ("coach_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

-- 4. FUNCTIONS

CREATE OR REPLACE FUNCTION "public"."book_session_with_credits"("p_user_id" "uuid", "p_session_id" bigint, "p_attendee_id" "uuid" DEFAULT NULL::"uuid") RETURNS json
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  v_credit_cost int;
  v_user_credits int;
begin
  select credit_cost into v_credit_cost from sessions where id = p_session_id;
  select credits into v_user_credits from profiles where id = p_user_id;

  if v_credit_cost is null then
    return json_build_object('success', false, 'message', 'Session cost not defined.');
  end if;

  if v_user_credits < v_credit_cost then
    return json_build_object('success', false, 'message', 'Insufficient credits.');
  end if;

  update profiles set credits = credits - v_credit_cost where id = p_user_id;
  
  -- Use attendee_id if provided, otherwise user_id
  insert into registrations (user_id, session_id) values (COALESCE(p_attendee_id, p_user_id), p_session_id);

  return json_build_object('success', true, 'message', 'Booking confirmed!', 'new_balance', v_user_credits - v_credit_cost);
end;
$$;

-- IMPORTANT: THIS IS THE UPDATED REFUND LOGIC (V1 SPEC)
CREATE OR REPLACE FUNCTION "public"."cancel_session_and_refund"(
  "p_attendee_id" "uuid", 
  "p_session_id" bigint
) 
RETURNS json
LANGUAGE "plpgsql" SECURITY DEFINER
AS $$
declare
  v_credit_cost int;
  v_start_time timestamp with time zone;
  v_payer_id uuid;
  v_hours_until_start float;
  v_refund_amount int;
begin
  -- 1. Check registration & get Payer
  SELECT payer_id INTO v_payer_id 
  FROM registrations 
  WHERE user_id = p_attendee_id AND session_id = p_session_id;

  if not found then
    return json_build_object('success', false, 'message', 'Booking not found.');
  end if;

  -- Default payer to attendee if null (legacy bookings)
  v_payer_id := COALESCE(v_payer_id, p_attendee_id);

  -- 2. Get Session Cost & Time
  SELECT credit_cost, start_time INTO v_credit_cost, v_start_time 
  FROM sessions 
  WHERE id = p_session_id;

  if v_credit_cost is null then
     -- Non-credit session, just delete
    DELETE FROM registrations WHERE user_id = p_attendee_id AND session_id = p_session_id;
    return json_build_object('success', true, 'message', 'Cancellation confirmed.');
  end if;

  -- 3. Calculate Hours until start
  v_hours_until_start := extract(epoch from (v_start_time - now())) / 3600;

  -- 4. Calculate Refund Amount based on Rules (0% < 24h, 50% < 48h)
  if v_hours_until_start < 24 then
    v_refund_amount := 0;
  elsif v_hours_until_start < 48 then
    v_refund_amount := floor(v_credit_cost * 0.5);
  else
    v_refund_amount := v_credit_cost;
  end if;

  -- 5. Refund Logic
  if v_refund_amount > 0 then
    UPDATE profiles SET credits = credits + v_refund_amount WHERE id = v_payer_id;
  end if;

  -- 6. Cancel Registration
  DELETE FROM registrations WHERE user_id = p_attendee_id AND session_id = p_session_id;

  return json_build_object(
    'success', true, 
    'message', 'Cancellation successful.', 
    'refund_amount', v_refund_amount,
    'hours_until', v_hours_until_start
  );
end;
$$;


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
    BEGIN
      INSERT INTO public.profiles (id, contact_email, first_name, last_name, username, avatar_url, role)
      VALUES (
        NEW.id, 
        NEW.email,
        split_part(NEW.email, '@', 1),
        '',
        split_part(NEW.email, '@', 1),
        'https://placehold.co/100',
        COALESCE(NEW.raw_user_meta_data->>'role', 'player')
      )
      ON CONFLICT (id) DO NOTHING;
      RETURN NEW;
    END;
    $$;


-- 5. GRANTS & RLS (SECURITY)

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."book_session_with_credits" TO "anon";
GRANT ALL ON FUNCTION "public"."book_session_with_credits" TO "authenticated";
GRANT ALL ON FUNCTION "public"."book_session_with_credits" TO "service_role";

GRANT ALL ON FUNCTION "public"."cancel_session_and_refund" TO "anon";
GRANT ALL ON FUNCTION "public"."cancel_session_and_refund" TO "authenticated";
GRANT ALL ON FUNCTION "public"."cancel_session_and_refund" TO "service_role";

GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";

-- GRANT TABLE ACCESS (RLS is enabled below, so this is safe base access)
GRANT ALL ON TABLE "public"."availability" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."likes" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."messages" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."player_relationships" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."players_stats" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."players_stats_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."posts" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."profiles" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."registrations" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."registrations_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."sessions" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."sessions_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."voice_commands" TO "anon", "authenticated", "service_role";

-- ============================================
-- ENABLE RLS ON ALL TABLES
-- ============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_commands ENABLE ROW LEVEL SECURITY;

-- ============================================
-- PROFILES TABLE POLICIES
-- ============================================

CREATE POLICY "Users can view own profile"
ON public.profiles FOR SELECT
USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
ON public.profiles FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

CREATE POLICY "Admins can view all profiles"
ON public.profiles FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

CREATE POLICY "Admins can update all profiles"
ON public.profiles FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

-- ============================================
-- REGISTRATIONS TABLE POLICIES
-- ============================================

CREATE POLICY "Users can view own registrations"
ON public.registrations FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can cancel own registrations"
ON public.registrations FOR DELETE
USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all registrations"
ON public.registrations FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

-- ============================================
-- SESSIONS TABLE POLICIES
-- ============================================

CREATE POLICY "Authenticated users can view sessions"
ON public.sessions FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Admins can create sessions"
ON public.sessions FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

CREATE POLICY "Admins can update sessions"
ON public.sessions FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

CREATE POLICY "Admins can delete sessions"
ON public.sessions FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

-- ============================================
-- PLAYERS_STATS TABLE POLICIES
-- ============================================

CREATE POLICY "Users can view own stats"
ON public.players_stats FOR SELECT
USING (auth.uid() = player_id);

CREATE POLICY "Public can view verified stats"
ON public.players_stats FOR SELECT
USING (is_verified = true);

CREATE POLICY "Coaches can verify stats"
ON public.players_stats FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() 
        AND profiles.role IN ('coach', 'admin')
    )
);

CREATE POLICY "Users can insert own stats"
ON public.players_stats FOR INSERT
WITH CHECK (auth.uid() = player_id AND is_verified = false);

-- ============================================
-- POSTS TABLE POLICIES
-- ============================================

CREATE POLICY "Users can view all posts"
ON public.posts FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Users can create own posts"
ON public.posts FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own posts"
ON public.posts FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own posts"
ON public.posts FOR DELETE
USING (auth.uid() = user_id);

-- ============================================
-- LIKES TABLE POLICIES
-- ============================================

CREATE POLICY "Users can view all likes"
ON public.likes FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Users can create own likes"
ON public.likes FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own likes"
ON public.likes FOR DELETE
USING (auth.uid() = user_id);

-- ============================================
-- MESSAGES TABLE POLICIES
-- ============================================

CREATE POLICY "Users can view sent messages"
ON public.messages FOR SELECT
USING (auth.uid() = sender_id);

CREATE POLICY "Users can view received messages"
ON public.messages FOR SELECT
USING (auth.uid() = receiver_id);

CREATE POLICY "Users can send messages"
ON public.messages FOR INSERT
WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "Users can delete sent messages"
ON public.messages FOR DELETE
USING (auth.uid() = sender_id);

-- ============================================
-- AVAILABILITY TABLE POLICIES
-- ============================================

CREATE POLICY "Users can view availability"
ON public.availability FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Coaches can manage own availability"
ON public.availability FOR ALL
USING (
    auth.uid() = coach_id 
    AND EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role IN ('coach', 'admin')
    )
);

CREATE POLICY "Admins can manage all availability"
ON public.availability FOR ALL
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

-- ============================================
-- VOICE_COMMANDS TABLE POLICIES
-- ============================================

CREATE POLICY "Coaches can view own voice commands"
ON public.voice_commands FOR SELECT
USING (auth.uid() = coach_id);

CREATE POLICY "Coaches can create own voice commands"
ON public.voice_commands FOR INSERT
WITH CHECK (
    auth.uid() = coach_id 
    AND EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role IN ('coach', 'admin')
    )
);

CREATE POLICY "Admins can view all voice commands"
ON public.voice_commands FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);
