-- ============================================================================
-- EAST APP HK - PRODUCTION DEPLOYMENT BUNDLE V2.1
-- Generated: January 18, 2026
-- Status: ✅ SYNCHRONIZED WITH LIVE DATABASE
-- ============================================================================
-- INSTRUCTIONS:
-- 1. Open your Supabase Project Dashboard (SQL Editor)
-- 2. Paste this entire file
-- 3. Click RUN
-- 4. Verify all RPCs and policies are created
-- ============================================================================

-- This bundle includes ALL recent optimizations:
-- ✅ Updated RPC functions with credits_paid tracking
-- ✅ Performance indexes (including Stripe)
-- ✅ Data integrity constraints (tier, role checks)
-- ✅ RLS policies for all tables including sessions
-- ✅ All missing columns added

-- To apply ONLY the recent QA fixes to an existing database, use:
-- database/qa_cleanup_production.sql instead

-- ============================================================================
-- 1. EXTENSIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 2. TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name text,
    last_name text,
    username text,
    role text CHECK (role IN ('player', 'coach', 'parent', 'sys-admin')) DEFAULT 'player',
    credits integer DEFAULT 0,
    team text,
    position text,
    avatar_url text,
    bio text,
    created_at timestamp with time zone DEFAULT now(),
    parent_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    contact_email text,
    mobile text,
    phone text,
    emergency_contact text,
    schedule_photo_url text,
    intro_video_url text,
    preferences jsonb DEFAULT '{}'::jsonb,
    gallery_images text[] DEFAULT '{}'::text[],
    
    -- Subscription & Payment
    tier text CHECK (tier IN ('free', 'individual', 'family_2', 'family_3plus')) DEFAULT 'free',
    membership_tier text CHECK (membership_tier IN ('individual', 'family_2', 'family_3plus')) DEFAULT 'individual',
    stripe_customer_id text,
    stripe_subscription_id text,
    subscription_status text DEFAULT 'inactive'
);

CREATE TABLE IF NOT EXISTS public.sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    description text,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    max_capacity integer DEFAULT 10,
    instructor text,
    image_url text,
    coach_image_url text,
    category text DEFAULT 'CLASS',
    credit_cost integer DEFAULT 10,
    session_type_id text,
    priority integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.registrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    session_id bigint REFERENCES public.sessions(id) ON DELETE CASCADE,
    attended boolean DEFAULT false,
    payer_id uuid REFERENCES public.profiles(id),
    credits_paid integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.availability (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status text CHECK (status IN ('available', 'booked', 'unavailable')) DEFAULT 'available',
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.session_types (
    id text PRIMARY KEY,
    title text NOT NULL,
    category text CHECK (category IN ('CLASS', 'PRIVATE', 'FACILITY')) NOT NULL,
    description text,
    image_url text,
    credit_cost integer DEFAULT 10,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.coach_services (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    service_type_id text REFERENCES public.session_types(id) ON DELETE CASCADE,
    tier text DEFAULT 'junior',
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(coach_id, service_type_id)
);

CREATE TABLE IF NOT EXISTS public.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    content text,
    image_url text,
    user_id uuid REFERENCES public.profiles(id),
    likes_count integer DEFAULT 0,
    shared_post_id bigint REFERENCES public.posts(id)
);

CREATE TABLE IF NOT EXISTS public.likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid NOT NULL,
    post_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    conversation_id text NOT NULL,
    sender_id uuid NOT NULL,
    content text NOT NULL,
    read boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.players_stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    category text NOT NULL,
    stats jsonb DEFAULT '{}'::jsonb,
    verified boolean DEFAULT false,
    verified_by uuid REFERENCES public.profiles(id),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.voice_commands (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    coach_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    command_text text NOT NULL,
    action_type text NOT NULL,
    parameters jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.player_relationships (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    parent_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    child_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    relationship_type varchar(50) DEFAULT 'parent_child',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 3. INDEXES (Performance Optimization)
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_registrations_user_id ON registrations(user_id);
CREATE INDEX IF NOT EXISTS idx_registrations_session_id ON registrations(session_id);
CREATE INDEX IF NOT EXISTS idx_availability_coach_id_time ON availability(coach_id, start_time);
CREATE INDEX IF NOT EXISTS idx_profiles_membership_tier ON profiles(membership_tier);
CREATE INDEX IF NOT EXISTS idx_profiles_stripe_customer_id ON profiles(stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_profiles_parent_id ON profiles(parent_id);

-- ============================================================================
-- 4. RPC FUNCTIONS (Atomic Transactions)
-- ============================================================================

-- Updated: Now stores credits_paid and payer_id correctly
CREATE OR REPLACE FUNCTION public.book_session_with_credits(
    p_user_id uuid,
    p_session_id bigint,
    p_attendee_id uuid DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_credit_cost int;
    v_user_credits int;
    v_sub_status text;
    v_final_attendee_id uuid;
    v_new_balance int;
BEGIN
    v_final_attendee_id := COALESCE(p_attendee_id, p_user_id);

    SELECT credit_cost INTO v_credit_cost FROM sessions WHERE id = p_session_id;
    SELECT credits, subscription_status INTO v_user_credits, v_sub_status 
    FROM profiles WHERE id = p_user_id;

    IF v_credit_cost IS NULL THEN
        RETURN json_build_object('success', false, 'message', 'Session cost not defined.');
    END IF;

    IF v_sub_status IS NULL OR (v_sub_status != 'active' AND v_sub_status != 'trialing') THEN
        RETURN json_build_object('success', false, 'message', 'Membership dormant. Renew to unlock credits.');
    END IF;

    IF v_user_credits < v_credit_cost THEN
        RETURN json_build_object('success', false, 'message', 'Insufficient credits.');
    END IF;

    UPDATE profiles SET credits = credits - v_credit_cost WHERE id = p_user_id
    RETURNING credits INTO v_new_balance;
    
    INSERT INTO registrations (user_id, session_id, payer_id, credits_paid) 
    VALUES (v_final_attendee_id, p_session_id, p_user_id, v_credit_cost);

    RETURN json_build_object('success', true, 'message', 'Booking confirmed!', 'new_balance', v_new_balance);
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Booking failed: ' || SQLERRM);
END;
$$;

CREATE OR REPLACE FUNCTION public.book_coach_atomic(
    p_user_id uuid,
    p_coach_id uuid,
    p_session_id bigint,
    p_credit_cost int,
    p_attendee_id uuid DEFAULT NULL,
    p_origin text DEFAULT 'facilities'
) RETURNS json AS $$
DECLARE
    v_user_credits int;
    v_new_balance int;
    v_final_attendee_id uuid;
BEGIN
    v_final_attendee_id := COALESCE(p_attendee_id, p_user_id);

    PERFORM * FROM availability 
    WHERE coach_id = p_coach_id 
    AND start_time <= (SELECT start_time FROM sessions WHERE id = p_session_id)
    AND end_time >= (SELECT end_time FROM sessions WHERE id = p_session_id)
    FOR UPDATE;
    
    SELECT credits INTO v_user_credits FROM profiles WHERE id = p_user_id;
    
    IF v_user_credits < p_credit_cost THEN
        RETURN json_build_object('success', false, 'message', 'Insufficient credits.', 'current_balance', v_user_credits);
    END IF;
    
    UPDATE profiles SET credits = credits - p_credit_cost WHERE id = p_user_id RETURNING credits INTO v_new_balance;
    
    INSERT INTO registrations (user_id, session_id, payer_id, credits_paid)
    VALUES (v_final_attendee_id, p_session_id, p_user_id, p_credit_cost);
    
    RETURN json_build_object('success', true, 'message', 'Booking confirmed!', 'new_balance', v_new_balance);
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Booking failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.cancel_session_and_refund(
    p_user_id uuid,
    p_session_id bigint
) RETURNS json AS $$
DECLARE
    v_credits_paid int;
    v_payer_id uuid;
    v_registration_id bigint;
BEGIN
    SELECT id, credits_paid, payer_id INTO v_registration_id, v_credits_paid, v_payer_id
    FROM registrations
    WHERE user_id = p_user_id AND session_id = p_session_id;

    IF v_registration_id IS NULL THEN
        RETURN json_build_object('success', false, 'message', 'Registration not found');
    END IF;

    DELETE FROM registrations WHERE id = v_registration_id;

    IF v_credits_paid > 0 THEN
        UPDATE profiles SET credits = credits + v_credits_paid WHERE id = v_payer_id;
    END IF;

    RETURN json_build_object('success', true, 'message', 'Session cancelled and refunds processed', 'refund_amount', v_credits_paid);
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Cancellation failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.transfer_credits(
    p_from_user_id uuid,
    p_to_user_id uuid,
    p_amount int
) RETURNS json AS $$
DECLARE
    v_from_credits int;
    v_to_credits int;
    v_parent_id uuid;
BEGIN
    IF p_amount <= 0 THEN 
        RETURN json_build_object('success', false, 'message', 'Transfer amount must be positive'); 
    END IF;

    SELECT credits INTO v_from_credits FROM profiles WHERE id = p_from_user_id;
    
    IF v_from_credits < p_amount THEN
        RETURN json_build_object('success', false, 'message', 'Insufficient credits');
    END IF;

    SELECT credits, parent_id INTO v_to_credits, v_parent_id FROM profiles WHERE id = p_to_user_id;
    
    IF v_parent_id != p_from_user_id THEN
        RETURN json_build_object('success', false, 'message', 'You can only transfer credits to your own children');
    END IF;

    UPDATE profiles SET credits = credits - p_amount WHERE id = p_from_user_id;
    UPDATE profiles SET credits = credits + p_amount WHERE id = p_to_user_id;

    RETURN json_build_object('success', true, 'message', 'Transfer successful', 'amount', p_amount);
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'message', 'Transfer failed: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.profiles (id, first_name, last_name, avatar_url, role, membership_tier, contact_email)
    VALUES (
        new.id,
        new.raw_user_meta_data->>'first_name',
        new.raw_user_meta_data->>'last_name',
        new.raw_user_meta_data->>'avatar_url',
        COALESCE(new.raw_user_meta_data->>'role', 'player'),
        'individual',
        new.email
    );
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- 5. TRIGGERS
-- ============================================================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- 6. ROW LEVEL SECURITY (RLS)
-- ============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_relationships ENABLE ROW LEVEL SECURITY;

-- Sessions Policies (Public Read, Admin Write)
DROP POLICY IF EXISTS "sessions_public_read" ON public.sessions;
CREATE POLICY "sessions_public_read" ON public.sessions FOR SELECT USING (true);

DROP POLICY IF EXISTS "sessions_service_role_all" ON public.sessions;
CREATE POLICY "sessions_service_role_all" ON public.sessions FOR ALL 
USING (auth.role() = 'service_role');

-- Profiles Policies
DROP POLICY IF EXISTS "profiles_public_read" ON public.profiles;
CREATE POLICY "profiles_public_read" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "profiles_own_update" ON public.profiles;
CREATE POLICY "profiles_own_update" ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

-- Registrations Policies
DROP POLICY IF EXISTS "registrations_own_read" ON public.registrations;
CREATE POLICY "registrations_own_read" ON public.registrations FOR SELECT 
USING (auth.uid() = user_id OR auth.uid() = payer_id);

DROP POLICY IF EXISTS "registrations_own_delete" ON public.registrations;
CREATE POLICY "registrations_own_delete" ON public.registrations FOR DELETE 
USING (auth.uid() = user_id OR auth.uid() = payer_id);

-- Session Types Policies
DROP POLICY IF EXISTS "session_types_public_read" ON public.session_types;
CREATE POLICY "session_types_public_read" ON public.session_types FOR SELECT USING (true);

-- Availability Policies
DROP POLICY IF EXISTS "availability_public_read" ON public.availability;
CREATE POLICY "availability_public_read" ON public.availability FOR SELECT USING (true);

-- ============================================================================
-- 7. GRANTS
-- ============================================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

GRANT SELECT ON public.profiles TO authenticated;
GRANT SELECT ON public.sessions TO authenticated;
GRANT SELECT ON public.availability TO authenticated;
GRANT SELECT ON public.session_types TO authenticated;

GRANT EXECUTE ON FUNCTION book_coach_atomic TO authenticated;
GRANT EXECUTE ON FUNCTION transfer_credits TO authenticated;
GRANT EXECUTE ON FUNCTION cancel_session_and_refund TO authenticated;
GRANT EXECUTE ON FUNCTION book_session_with_credits TO authenticated;

-- ============================================================================
-- END OF BUNDLE
-- ============================================================================

NOTIFY pgrst, 'reload schema';
