const { createClient } = require('@supabase/supabase-js');
const dotenv = require('dotenv');
const path = require('path');

// Load environment variables
dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
    console.error('❌ Missing environment variables');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function runMigration() {
    console.log('🚀 Starting Coach Schedule Fix Migration...\n');

    try {
        // 1. Create session_types table
        console.log('1. Creating session_types table...');
        const { error: createTableError } = await supabase.rpc('exec_sql', {
            query: `
                CREATE TABLE IF NOT EXISTS session_types (
                    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    title text NOT NULL,
                    category text,
                    description text,
                    image_url text,
                    credit_cost integer DEFAULT 100,
                    created_at timestamptz DEFAULT now()
                );
            `
        });

        if (createTableError) {
            console.log('⚠️  Using direct table creation (exec_sql not available)');
            // Try direct approach - check if table exists
            const { data: existingTable } = await supabase
                .from('session_types')
                .select('id')
                .limit(1);

            if (!existingTable) {
                console.log('❌ session_types table does not exist and cannot be created automatically.');
                console.log('Please run the SQL manually in Supabase Dashboard.');
                return;
            }
        }
        console.log('✅ session_types table ready');

        // 2. Check current schema
        console.log('\n2. Checking current sessions schema...');
        const { data: sessionSample, error: sessionError } = await supabase
            .from('sessions')
            .select('*')
            .limit(1);

        if (sessionSample && sessionSample.length > 0) {
            const columns = Object.keys(sessionSample[0]);
            console.log('Current columns:', columns.join(', '));

            const missingColumns = [];
            if (!columns.includes('session_type_id')) missingColumns.push('session_type_id');
            if (!columns.includes('status')) missingColumns.push('status');
            if (!columns.includes('max_capacity')) missingColumns.push('max_capacity');

            if (missingColumns.length > 0) {
                console.log('⚠️  Missing columns:', missingColumns.join(', '));
                console.log('\n❌ Cannot add columns automatically via Supabase client.');
                console.log('\n📋 Please run this SQL in Supabase Dashboard → SQL Editor:\n');
                console.log('─'.repeat(60));
                console.log(`
-- Add missing columns to sessions
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS session_type_id bigint REFERENCES session_types(id) ON DELETE SET NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS max_capacity integer DEFAULT 1;

-- Add missing columns to registrations
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS credits_paid integer;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_sessions_session_type_id ON sessions(session_type_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions(status);
CREATE INDEX IF NOT EXISTS idx_registrations_status ON registrations(status);

-- Update existing records
UPDATE sessions SET status = 'active' WHERE status IS NULL;
UPDATE registrations SET status = 'active' WHERE status IS NULL;
                `.trim());
                console.log('─'.repeat(60));
            } else {
                console.log('✅ All required columns exist!');
            }
        } else {
            console.log('⚠️  No sessions found, but table structure should be updated.');
        }

        console.log('\n✅ Migration check completed!');

    } catch (error) {
        console.error('\n❌ Error:', error.message);
    }
}

runMigration();
