


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
-- SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."book_session_with_credits"("p_user_id" "uuid", "p_session_id" bigint, "p_attendee_id" "uuid" DEFAULT NULL::"uuid") RETURNS json
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  v_credit_cost int;
  v_user_credits int;
begin
  select credit_cost into v_credit_cost from sessions where id = p_session_id;
  select credits into v_user_credits from profiles where id = p_user_id;

  if v_credit_cost is null then
    return json_build_object('success', false, 'message', 'Session cost not defined.');
  end if;

  if v_user_credits < v_credit_cost then
    return json_build_object('success', false, 'message', 'Insufficient credits.');
  end if;

  update profiles set credits = credits - v_credit_cost where id = p_user_id;
  
  -- Use attendee_id if provided, otherwise user_id
  -- Track payer_id for refund logic (parent booking for child)
  insert into registrations (user_id, session_id, payer_id) values (COALESCE(p_attendee_id, p_user_id), p_session_id, p_user_id);

  return json_build_object('success', true, 'message', 'Booking confirmed!', 'new_balance', v_user_credits - v_credit_cost);
end;
$$;


ALTER FUNCTION "public"."book_session_with_credits"("p_user_id" "uuid", "p_session_id" bigint, "p_attendee_id" "uuid") OWNER TO "postgres";


create or replace function cancel_session_and_refund(
  p_attendee_id uuid,
  p_session_id bigint
)
returns json
language plpgsql
security definer
as $$
declare
  v_credit_cost int;
  v_payer_id uuid;
begin
  -- Check registration and get Payer
  SELECT payer_id INTO v_payer_id 
  FROM registrations 
  WHERE user_id = p_attendee_id AND session_id = p_session_id;

  if not found then
    return json_build_object('success', false, 'message', 'Booking not found.');
  end if;

  -- Default payer to attendee if null
  v_payer_id := COALESCE(v_payer_id, p_attendee_id);

  select credit_cost into v_credit_cost from sessions where id = p_session_id;

  if v_credit_cost is null then
    delete from registrations where user_id = p_attendee_id and session_id = p_session_id;
    return json_build_object('success', true, 'message', 'Cancellation confirmed.');
  end if;

  -- Refund PAYER
  update profiles set credits = credits + v_credit_cost where id = v_payer_id;
  delete from registrations where user_id = p_attendee_id and session_id = p_session_id;

  return json_build_object('success', true, 'message', 'Cancellation successful. Credits refunded.', 'refund_amount', v_credit_cost);
end;
$$;


ALTER FUNCTION "public"."cancel_session_and_refund"("p_attendee_id" "uuid", "p_session_id" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
    BEGIN
      INSERT INTO public.profiles (id, contact_email, first_name, last_name, username, avatar_url, role)
      VALUES (
        NEW.id, 
        NEW.email,
        split_part(NEW.email, '@', 1),
        '',
        split_part(NEW.email, '@', 1),
        'https://placehold.co/100',
        COALESCE(NEW.raw_user_meta_data->>'role', 'player')
      )
      ON CONFLICT (id) DO NOTHING;
      RETURN NEW;
    END;
    $$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."availability" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "coach_id" "uuid",
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "is_recurring" boolean DEFAULT false,
    "status" "text" DEFAULT 'available'::"text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."availability" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."likes" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "post_id" bigint
);


ALTER TABLE "public"."likes" OWNER TO "postgres";


ALTER TABLE "public"."likes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."likes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint NOT NULL,
    "sender_id" "uuid",
    "receiver_id" "uuid",
    "content" "text",
    "image_url" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "shared_event_id" bigint
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."player_relationships" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "parent_id" "uuid",
    "child_id" "uuid",
    "relationship_type" character varying(50) DEFAULT 'parent_child'::character varying,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."player_relationships" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."players_stats" (
    "id" bigint NOT NULL,
    "player_id" "uuid",
    "age" integer,
    "season" integer,
    "team" "text",
    "games_played_season" integer,
    "games_played_total" integer,
    "games_missed_healthy" integer,
    "games_missed_injured" integer,
    "goals_season" integer,
    "goals_total" integer,
    "assists_season" integer,
    "assists_total" integer,
    "gp" integer,
    "points" integer,
    "gwg" integer,
    "ppg" integer,
    "shg" integer,
    "pim" integer,
    "top_scorer_team" boolean,
    "top_scorer_league" boolean,
    "least_pim_team" boolean,
    "most_shots_team" boolean,
    "is_verified" boolean DEFAULT false,
    "verified_by" "uuid",
    "verified_at" timestamp with time zone,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."players_stats" OWNER TO "postgres";


ALTER TABLE "public"."players_stats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."players_stats_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."posts" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "image_url" "text",
    "caption" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "shared_post_id" bigint
);


ALTER TABLE "public"."posts" OWNER TO "postgres";


ALTER TABLE "public"."posts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."posts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "username" "text",
    "first_name" "text",
    "last_name" "text",
    "mobile" "text",
    "contact_email" "text",
    "avatar_url" "text",
    "bio" "text",
    "tier" "text" DEFAULT 'free'::"text",
    "stripe_customer_id" "text",
    "stripe_subscription_id" "text",
    "subscription_status" "text" DEFAULT 'inactive'::"text",
    "credits" integer DEFAULT 100,
    "gallery_images" "text"[] DEFAULT '{}'::"text"[],
    "schedule_photo_url" "text",
    "role" "text" DEFAULT 'player'::"text",
    "parent_id" "uuid",
    "intro_video_url" "text",
    "preferences" "jsonb" DEFAULT '{}'::"jsonb",
    "team" "text",
    "position" "text",
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."registrations" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "session_id" bigint NOT NULL,
    "registered_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "payer_id" "uuid"
);


ALTER TABLE "public"."registrations" OWNER TO "postgres";


ALTER TABLE "public"."registrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."registrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sessions" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "category" "text",
    "instructor" "text",
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "image_url" "text",
    "coach_image_url" "text",
    "description" "text",
    "credit_cost" integer DEFAULT 10
);


ALTER TABLE "public"."sessions" OWNER TO "postgres";


ALTER TABLE "public"."sessions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sessions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."voice_commands" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "coach_id" "uuid",
    "command_text" "text" NOT NULL,
    "processed_json" "jsonb",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."voice_commands" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS public.transactions (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount integer NOT NULL,
    type text NOT NULL CHECK (type IN ('topup', 'membership', 'transfer', 'booking', 'refund')),
    stripe_session_id text UNIQUE, 
    description text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."transactions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS public.check_ins (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    location_id text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."check_ins" OWNER TO "postgres";

CREATE OR REPLACE VIEW public.check_in_leaderboard AS
SELECT 
    user_id as player_id,
    count(id) as checkin_count
FROM public.check_ins
GROUP BY user_id;

ALTER TABLE "public"."check_in_leaderboard" OWNER TO "postgres";



ALTER TABLE ONLY "public"."availability"
    ADD CONSTRAINT "availability_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_user_id_post_id_key" UNIQUE ("user_id", "post_id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."player_relationships"
    ADD CONSTRAINT "player_relationships_parent_id_child_id_key" UNIQUE ("parent_id", "child_id");



ALTER TABLE ONLY "public"."player_relationships"
    ADD CONSTRAINT "player_relationships_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."players_stats"
    ADD CONSTRAINT "players_stats_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."registrations"
    ADD CONSTRAINT "registrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."registrations"
    ADD CONSTRAINT "registrations_user_id_session_id_key" UNIQUE ("user_id", "session_id");



ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."voice_commands"
    ADD CONSTRAINT "voice_commands_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."availability"
    ADD CONSTRAINT "availability_coach_id_fkey" FOREIGN KEY ("coach_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id");



ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."player_relationships"
    ADD CONSTRAINT "player_relationships_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."players_stats"
    ADD CONSTRAINT "players_stats_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."players_stats"
    ADD CONSTRAINT "players_stats_verified_by_fkey" FOREIGN KEY ("verified_by") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_shared_post_id_fkey" FOREIGN KEY ("shared_post_id") REFERENCES "public"."posts"("id");



ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."registrations"
    ADD CONSTRAINT "registrations_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."registrations"
    ADD CONSTRAINT "registrations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."voice_commands"
    ADD CONSTRAINT "voice_commands_coach_id_fkey" FOREIGN KEY ("coach_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



-- RLS SECURITY & COLUMN PRIVILEGES
-- Sensitive columns (credits, role) are protected by REVOKE UPDATE from authenticated role.
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."registrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."players_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."likes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."availability" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."voice_commands" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."player_relationships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."transactions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";









GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";































































































































































GRANT ALL ON FUNCTION "public"."book_session_with_credits"("p_user_id" "uuid", "p_session_id" bigint, "p_attendee_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."book_session_with_credits"("p_user_id" "uuid", "p_session_id" bigint, "p_attendee_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."book_session_with_credits"("p_user_id" "uuid", "p_session_id" bigint, "p_attendee_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."cancel_session_and_refund"("p_user_id" "uuid", "p_session_id" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."cancel_session_and_refund"("p_user_id" "uuid", "p_session_id" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."cancel_session_and_refund"("p_user_id" "uuid", "p_session_id" bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."availability" TO "anon";
GRANT ALL ON TABLE "public"."availability" TO "authenticated";
GRANT ALL ON TABLE "public"."availability" TO "service_role";



GRANT ALL ON TABLE "public"."likes" TO "anon";
GRANT ALL ON TABLE "public"."likes" TO "authenticated";
GRANT ALL ON TABLE "public"."likes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."player_relationships" TO "anon";
GRANT ALL ON TABLE "public"."player_relationships" TO "authenticated";
GRANT ALL ON TABLE "public"."player_relationships" TO "service_role";



GRANT ALL ON TABLE "public"."players_stats" TO "anon";
GRANT ALL ON TABLE "public"."players_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."players_stats" TO "service_role";



GRANT ALL ON SEQUENCE "public"."players_stats_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."players_stats_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."players_stats_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."posts" TO "anon";
GRANT ALL ON TABLE "public"."posts" TO "authenticated";
GRANT ALL ON TABLE "public"."posts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."registrations" TO "anon";
GRANT ALL ON TABLE "public"."registrations" TO "authenticated";
GRANT ALL ON TABLE "public"."registrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."registrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."registrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."registrations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sessions" TO "anon";
GRANT ALL ON TABLE "public"."sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."sessions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sessions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sessions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sessions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."voice_commands" TO "anon";
GRANT ALL ON TABLE "public"."voice_commands" TO "authenticated";
GRANT ALL ON TABLE "public"."voice_commands" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
































-- =========================================================================
-- FILM ROOM SESSIONS & TIMESTAMPS
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.film_room_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    coach_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    youtube_url TEXT NOT NULL,
    video_id TEXT NOT NULL,
    target_type TEXT NOT NULL DEFAULT 'all' CHECK (target_type IN ('all', 'team', 'player')),
    target_team_id UUID REFERENCES public.teams(id) ON DELETE SET NULL,
    target_player_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.film_room_timestamps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES public.film_room_sessions(id) ON DELETE CASCADE,
    timestamp_seconds INTEGER NOT NULL DEFAULT 0,
    timestamp_label TEXT NOT NULL DEFAULT '00:00',
    title TEXT NOT NULL,
    notes TEXT DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_film_room_sessions_coach ON public.film_room_sessions(coach_id);
CREATE INDEX IF NOT EXISTS idx_film_room_sessions_target_team ON public.film_room_sessions(target_team_id);
CREATE INDEX IF NOT EXISTS idx_film_room_sessions_target_player ON public.film_room_sessions(target_player_id);
CREATE INDEX IF NOT EXISTS idx_film_room_timestamps_session ON public.film_room_timestamps(session_id);

ALTER TABLE public.film_room_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.film_room_timestamps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Film sessions readable by target audience" ON public.film_room_sessions
    FOR SELECT TO authenticated
    USING (
        auth.uid() = coach_id
        OR target_type = 'all'
        OR target_player_id = auth.uid()
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role IN ('admin', 'sys-admin')
        )
        OR EXISTS (
            SELECT 1 FROM public.team_members tm
            WHERE tm.team_id = film_room_sessions.target_team_id AND tm.user_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1 FROM public.profiles player
            WHERE player.id = film_room_sessions.target_player_id AND player.parent_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1 FROM public.messages m
            WHERE m.shared_film_session_id = film_room_sessions.id
              AND (
                  m.receiver_id = auth.uid()
                  OR m.sender_id = auth.uid()
                  OR (m.team_id IS NOT NULL AND EXISTS (
                      SELECT 1 FROM public.team_members tm WHERE tm.team_id = m.team_id AND tm.user_id = auth.uid()
                  ))
              )
        )
    );

CREATE POLICY "Coaches and admins can manage film sessions" ON public.film_room_sessions
    FOR ALL TO authenticated
    USING (
        auth.uid() = coach_id
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role IN ('admin', 'sys-admin')
        )
    )
    WITH CHECK (
        auth.uid() = coach_id
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id = auth.uid() AND p.role IN ('admin', 'sys-admin')
        )
    );

-- Table: public.player_hockey_stats
CREATE TABLE IF NOT EXISTS public.player_hockey_stats (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    season TEXT NOT NULL,
    team_name TEXT NOT NULL,
    division TEXT NOT NULL DEFAULT 'U13',
    competition_name TEXT NOT NULL,
    competition_type TEXT NOT NULL DEFAULT 'TOURNAMENT' CHECK (competition_type IN ('TOURNAMENT', 'LEAGUE', 'EXHIBITION', 'CAMP')),
    position_type TEXT NOT NULL DEFAULT 'SKATER' CHECK (position_type IN ('SKATER', 'GOALIE')),
    jersey_number INTEGER,
    position TEXT,
    gp INTEGER DEFAULT 0,
    goals INTEGER DEFAULT 0,
    assists INTEGER DEFAULT 0,
    points INTEGER DEFAULT 0,
    pim INTEGER DEFAULT 0,
    ppg INTEGER DEFAULT 0,
    shg INTEGER DEFAULT 0,
    gwg INTEGER DEFAULT 0,
    minutes_played INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    losses INTEGER DEFAULT 0,
    otl INTEGER DEFAULT 0,
    goals_against INTEGER DEFAULT 0,
    gaa NUMERIC(4,2) DEFAULT 0.00,
    shots_against INTEGER DEFAULT 0,
    saves INTEGER DEFAULT 0,
    save_pct NUMERIC(5,3) DEFAULT 0.000,
    shutouts INTEGER DEFAULT 0,
    accolades TEXT[] DEFAULT '{}'::TEXT[],
    is_verified BOOLEAN DEFAULT true,
    verified_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_player_season_competition UNIQUE (player_id, season, competition_name, team_name)
);

