CREATE TABLE IF NOT EXISTS players_stats (
  player_id SERIAL PRIMARY KEY,
  age INTEGER,
  season INTEGER,
  team VARCHAR(255),
  games_played_season INTEGER,
  games_played_total INTEGER,
  games_missed_healthy INTEGER,
  games_missed_injured INTEGER,
  goals_season INTEGER,
  goals_total INTEGER,
  assists_season INTEGER,
  assists_total INTEGER,
  gp INTEGER,
  points INTEGER,
  gwg INTEGER,
  ppg INTEGER,
  shg INTEGER,
  pim INTEGER,
  top_scorer_team BOOLEAN,
  top_scorer_league BOOLEAN,
  least_pim_team BOOLEAN,
  most_shots_team BOOLEAN,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);