var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/announcements/route.js")
R.c("server/chunks/[root-of-the-server]__0651337d._.js")
R.c("server/chunks/[root-of-the-server]__42a428ae._.js")
R.c("server/chunks/_7f1565d1._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_b8a57c16._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_announcements_route_actions_0c93eaf2.js")
R.m(38610)
module.exports=R.m(38610).exports
