-- Fix Coach Schedule: Add Missing Columns
-- This migration adds the required columns to sessions and registrations tables
-- that are needed for schedule generation to work properly.

-- 1. Create session_types table if it doesn't exist
CREATE TABLE IF NOT EXISTS session_types (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    category text,
    description text,
    image_url text,
    credit_cost integer DEFAULT 100,
    created_at timestamptz DEFAULT now()
);

-- Enable RLS for session_types
ALTER TABLE session_types ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON TABLE session_types TO anon;
GRANT ALL ON TABLE session_types TO authenticated;
GRANT ALL ON TABLE session_types TO service_role;

-- 2. Add missing columns to sessions table
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS session_type_id bigint REFERENCES session_types(id) ON DELETE SET NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS max_capacity integer DEFAULT 1;

-- 3. Add missing columns to registrations table
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS credits_paid integer;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- 4. Create index for better performance
CREATE INDEX IF NOT EXISTS idx_sessions_session_type_id ON sessions(session_type_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions(status);
CREATE INDEX IF NOT EXISTS idx_registrations_status ON registrations(status);

-- 5. Update existing sessions to have active status if null
UPDATE sessions SET status = 'active' WHERE status IS NULL;
UPDATE registrations SET status = 'active' WHERE status IS NULL;

-- Notify schema reload
NOTIFY pgrst, 'reload schema';
