var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin-ops/bookings/route.js")
R.c("server/chunks/[root-of-the-server]__cd91125a._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/[root-of-the-server]__42a428ae._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_admin-ops_bookings_route_actions_ea450924.js")
R.m(89976)
module.exports=R.m(89976).exports
