// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin-debug" | "/admin-login" | "/admin-ops" | "/admin-ops/bookings" | "/admin-ops/coaches" | "/admin-ops/schedule" | "/admin-ops/services" | "/auth/update-password" | "/calendar" | "/check-in" | "/community" | "/faq" | "/forgot-password" | "/login" | "/membership" | "/membership/success" | "/privacy" | "/profile/[id]" | "/public/coach/[id]" | "/public/player/[id]" | "/statistics" | "/stats" | "/support" | "/sys-admin" | "/sys-admin/audit" | "/sys-admin/bookings" | "/sys-admin/coaches" | "/sys-admin/directory" | "/sys-admin/events" | "/sys-admin/leaderboard" | "/sys-admin/metrics" | "/sys-admin/news" | "/sys-admin/player-stats" | "/sys-admin/players" | "/sys-admin/qr" | "/sys-admin/schedule" | "/sys-admin/services" | "/sys-admin/stats" | "/sys-admin/transactions" | "/system-check" | "/terms" | "/test-auth" | "/test-direct" | "/top-up"
type AppRouteHandlerRoutes = "/api/admin-ops/bookings" | "/api/admin/adjust-credits" | "/api/admin/announcements" | "/api/admin/bookings" | "/api/admin/coach-availability" | "/api/admin/create-coach" | "/api/admin/create-player" | "/api/admin/delete-coach" | "/api/admin/delete-player" | "/api/admin/generate-schedule" | "/api/admin/leaderboard" | "/api/admin/metrics" | "/api/admin/ocr-stats" | "/api/admin/player-stats" | "/api/admin/portal" | "/api/admin/schedule" | "/api/admin/send-reset-email" | "/api/admin/services" | "/api/admin/sessions" | "/api/admin/transactions" | "/api/admin/update-coach" | "/api/admin/update-player" | "/api/announcements" | "/api/auth/register" | "/api/auth/request-reset" | "/api/auth/send-welcome-email" | "/api/check-in" | "/api/checkout" | "/api/coach/master-schedule" | "/api/coach/notes" | "/api/coaches/available" | "/api/cron/reminders" | "/api/debug" | "/api/debug-email" | "/api/debug-env" | "/api/family/add-child" | "/api/family/provision-player" | "/api/family/transfer-credits" | "/api/health" | "/api/my-schedule" | "/api/player-stats" | "/api/register" | "/api/sessions" | "/api/sessions/book" | "/api/sessions/cancel" | "/api/sessions/pay-via-qr" | "/api/stripe/test-confirm" | "/api/user/repair-profile" | "/api/user/transactions" | "/api/user/transfer-credits" | "/api/webhooks/stripe" | "/inngest"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin-ops" | "/check-in" | "/sys-admin"
type RedirectRoutes = never
type RewriteRoutes = "/supabase/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin-debug": {}
  "/admin-login": {}
  "/admin-ops": {}
  "/admin-ops/bookings": {}
  "/admin-ops/coaches": {}
  "/admin-ops/schedule": {}
  "/admin-ops/services": {}
  "/api/admin-ops/bookings": {}
  "/api/admin/adjust-credits": {}
  "/api/admin/announcements": {}
  "/api/admin/bookings": {}
  "/api/admin/coach-availability": {}
  "/api/admin/create-coach": {}
  "/api/admin/create-player": {}
  "/api/admin/delete-coach": {}
  "/api/admin/delete-player": {}
  "/api/admin/generate-schedule": {}
  "/api/admin/leaderboard": {}
  "/api/admin/metrics": {}
  "/api/admin/ocr-stats": {}
  "/api/admin/player-stats": {}
  "/api/admin/portal": {}
  "/api/admin/schedule": {}
  "/api/admin/send-reset-email": {}
  "/api/admin/services": {}
  "/api/admin/sessions": {}
  "/api/admin/transactions": {}
  "/api/admin/update-coach": {}
  "/api/admin/update-player": {}
  "/api/announcements": {}
  "/api/auth/register": {}
  "/api/auth/request-reset": {}
  "/api/auth/send-welcome-email": {}
  "/api/check-in": {}
  "/api/checkout": {}
  "/api/coach/master-schedule": {}
  "/api/coach/notes": {}
  "/api/coaches/available": {}
  "/api/cron/reminders": {}
  "/api/debug": {}
  "/api/debug-email": {}
  "/api/debug-env": {}
  "/api/family/add-child": {}
  "/api/family/provision-player": {}
  "/api/family/transfer-credits": {}
  "/api/health": {}
  "/api/my-schedule": {}
  "/api/player-stats": {}
  "/api/register": {}
  "/api/sessions": {}
  "/api/sessions/book": {}
  "/api/sessions/cancel": {}
  "/api/sessions/pay-via-qr": {}
  "/api/stripe/test-confirm": {}
  "/api/user/repair-profile": {}
  "/api/user/transactions": {}
  "/api/user/transfer-credits": {}
  "/api/webhooks/stripe": {}
  "/auth/update-password": {}
  "/calendar": {}
  "/check-in": {}
  "/community": {}
  "/faq": {}
  "/forgot-password": {}
  "/inngest": {}
  "/login": {}
  "/membership": {}
  "/membership/success": {}
  "/privacy": {}
  "/profile/[id]": { "id": string; }
  "/public/coach/[id]": { "id": string; }
  "/public/player/[id]": { "id": string; }
  "/statistics": {}
  "/stats": {}
  "/supabase/[[...path]]": { "path"?: string[]; }
  "/support": {}
  "/sys-admin": {}
  "/sys-admin/audit": {}
  "/sys-admin/bookings": {}
  "/sys-admin/coaches": {}
  "/sys-admin/directory": {}
  "/sys-admin/events": {}
  "/sys-admin/leaderboard": {}
  "/sys-admin/metrics": {}
  "/sys-admin/news": {}
  "/sys-admin/player-stats": {}
  "/sys-admin/players": {}
  "/sys-admin/qr": {}
  "/sys-admin/schedule": {}
  "/sys-admin/services": {}
  "/sys-admin/stats": {}
  "/sys-admin/transactions": {}
  "/system-check": {}
  "/terms": {}
  "/test-auth": {}
  "/test-direct": {}
  "/top-up": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin-ops": never
  "/check-in": never
  "/sys-admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
