var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/checkout/route.js")
R.c("server/chunks/node_modules_next_1e868c1f._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_stripe_esm_e3c80d40._.js")
R.c("server/chunks/node_modules_svix_dist_7132ddd4._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_17731919._.js")
R.c("server/chunks/[root-of-the-server]__7e8831e0._.js")
R.c("server/chunks/_next-internal_server_app_api_checkout_route_actions_414bfd84.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/checkout/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/checkout/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
