var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__01198b53._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_54f83cae.js")
R.c("server/chunks/ssr/[root-of-the-server]__947e3ce5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d5ae7ad._.js")
R.c("server/chunks/ssr/node_modules_e8d7973e._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4f822c68._.js")
R.c("server/chunks/ssr/app_error_tsx_5275429f._.js")
R.c("server/chunks/ssr/app_loading_tsx_b05711b0._.js")
R.c("server/chunks/ssr/app_not-found_tsx_339d4b53._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(23010)
module.exports=R.m(23010).exports
