import { createClient, SupabaseClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import { purgeUserData } from './db-cleanup';

dotenv.config({ path: path.resolve(__dirname, '../../.env.local') });

export class TestFactory {
    private static _supabase: SupabaseClient | null = null;
    private static createdUserIds: string[] = [];
    private static createdSessionIds: number[] = [];
    private static createdServiceIds: string[] = [];

    static get supabase(): SupabaseClient {
        if (!this._supabase) {
            const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
            const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
            this._supabase = createClient(supabaseUrl, supabaseKey, {
                auth: { autoRefreshToken: false, persistSession: false }
            });
        }
        return this._supabase;
    }

    /**
     * Creates a test user with a specific role and optional initial credits.
     */
    static async createUser(options: {
        role: 'parent' | 'coach' | 'player' | 'sys-admin';
        firstName?: string;
        lastName?: string;
        credits?: number;
        accountStatus?: 'active' | 'pending' | 'suspended';
    }) {
        const timestamp = Date.now();
        const email = `test-${options.role}-${timestamp}@pw.test`;
        const password = 'TestPassword123!';
        const firstName = options.firstName || `Test${options.role.charAt(0).toUpperCase() + options.role.slice(1)}`;
        const lastName = options.lastName || `User${timestamp.toString().slice(-4)}`;

        const { data: authData, error: authError } = await this.supabase.auth.admin.createUser({
            email,
            password,
            email_confirm: true,
            user_metadata: { first_name: firstName, last_name: lastName, role: options.role }
        });

        if (authError || !authData.user) {
            throw new Error(`[TestFactory] Failed to create ${options.role}: ${authError?.message}`);
        }

        const userId = authData.user.id;
        this.createdUserIds.push(userId);

        const { error: profileError } = await this.supabase.from('profiles').upsert({
            id: userId,
            first_name: firstName,
            last_name: lastName,
            username: email,
            contact_email: email,
            role: options.role,
            credits: options.credits ?? 100,
            account_status: options.accountStatus || 'active'
        });

        if (profileError) {
            throw new Error(`[TestFactory] Failed to upsert profile: ${profileError.message}`);
        }

        return {
            id: userId,
            email,
            password,
            firstName,
            lastName,
            role: options.role
        };
    }

    /**
     * Creates a test class service and future session.
     */
    static async createClassSession(options: {
        title?: string;
        daysInFuture?: number;
        creditCost?: number;
        maxCapacity?: number;
    }) {
        const title = options.title || `Factory Test Class ${Date.now()}`;
        const daysInFuture = options.daysInFuture ?? 1;
        const creditCost = options.creditCost ?? 5;
        const maxCapacity = options.maxCapacity ?? 10;

        // 1. Create Service
        const { data: service, error: svcError } = await this.supabase
            .from('session_types')
            .insert({
                title,
                category: 'CLASS',
                description: 'Generated by TestFactory',
                image_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600'
            })
            .select()
            .single();

        if (svcError || !service) throw new Error(`[TestFactory] Service creation failed: ${svcError?.message}`);
        this.createdServiceIds.push(service.id);

        // 2. Create Session
        const startTime = new Date();
        startTime.setDate(startTime.getDate() + daysInFuture);
        startTime.setHours(10, 0, 0, 0);
        const endTime = new Date(startTime.getTime() + 60 * 60 * 1000);

        const { data: session, error: sessError } = await this.supabase
            .from('sessions')
            .insert({
                title,
                description: 'Generated by TestFactory',
                start_time: startTime.toISOString(),
                end_time: endTime.toISOString(),
                category: 'CLASS',
                session_type_id: service.id,
                instructor: 'Coach Factory',
                total_facility_bays: 1,
                max_capacity: maxCapacity,
                credit_cost: creditCost
            })
            .select()
            .single();

        if (sessError || !session) throw new Error(`[TestFactory] Session creation failed: ${sessError?.message}`);
        this.createdSessionIds.push(session.id);

        return { service, session };
    }

    /**
     * Clean up all entities created by the factory during the test run.
     */
    static async cleanup() {
        // 1. Delete created sessions & registrations
        if (this.createdSessionIds.length > 0) {
            await this.supabase.from('registrations').delete().in('session_id', this.createdSessionIds);
            await this.supabase.from('sessions').delete().in('id', this.createdSessionIds);
            this.createdSessionIds = [];
        }

        // 2. Delete created services
        if (this.createdServiceIds.length > 0) {
            await this.supabase.from('session_types').delete().in('id', this.createdServiceIds);
            this.createdServiceIds = [];
        }

        // 3. Purge users via cascading cleaner
        if (this.createdUserIds.length > 0) {
            await purgeUserData(this.supabase, this.createdUserIds);
            this.createdUserIds = [];
        }
    }
}
