name: 🚀 Deploy to Vercel (Test)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_dHuuSP1b4oQVAiWNVn2Rvgg8
          VERCEL_PROJECT_ID: prj_MjBg7CY0uxNIKJxwtkws9Kf1tKOA

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_dHuuSP1b4oQVAiWNVn2Rvgg8
          VERCEL_PROJECT_ID: prj_MjBg7CY0uxNIKJxwtkws9Kf1tKOA

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_dHuuSP1b4oQVAiWNVn2Rvgg8
          VERCEL_PROJECT_ID: prj_MjBg7CY0uxNIKJxwtkws9Kf1tKOA
